// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: shared/proto/rag/v1/rag.proto

package ragv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Document represents an uploaded document.
type Document struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId           string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name               string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	FileType           string                 `protobuf:"bytes,5,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	FileSize           int64                  `protobuf:"varint,6,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Status             string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	ProgressPercentage int32                  `protobuf:"varint,8,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_shared_proto_rag_v1_rag_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Document) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Document) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Document) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *Document) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *Document) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Document) GetProgressPercentage() int32 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

func (x *Document) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Document) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// UploadDocumentRequest uploads a new document.
type UploadDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	FileContent   []byte                 `protobuf:"bytes,3,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	FileType      string                 `protobuf:"bytes,4,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDocumentRequest) Reset() {
	*x = UploadDocumentRequest{}
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocumentRequest) ProtoMessage() {}

func (x *UploadDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocumentRequest.ProtoReflect.Descriptor instead.
func (*UploadDocumentRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_rag_v1_rag_proto_rawDescGZIP(), []int{1}
}

func (x *UploadDocumentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadDocumentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UploadDocumentRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *UploadDocumentRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

// UploadDocumentResponse confirms upload.
type UploadDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDocumentResponse) Reset() {
	*x = UploadDocumentResponse{}
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocumentResponse) ProtoMessage() {}

func (x *UploadDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocumentResponse.ProtoReflect.Descriptor instead.
func (*UploadDocumentResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_rag_v1_rag_proto_rawDescGZIP(), []int{2}
}

func (x *UploadDocumentResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *UploadDocumentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// ListDocumentsRequest lists documents with pagination.
type ListDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsRequest) Reset() {
	*x = ListDocumentsRequest{}
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsRequest) ProtoMessage() {}

func (x *ListDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_rag_v1_rag_proto_rawDescGZIP(), []int{3}
}

func (x *ListDocumentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDocumentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListDocumentsResponse returns paginated documents.
type ListDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsResponse) Reset() {
	*x = ListDocumentsResponse{}
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsResponse) ProtoMessage() {}

func (x *ListDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_rag_v1_rag_proto_rawDescGZIP(), []int{4}
}

func (x *ListDocumentsResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *ListDocumentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListDocumentsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDocumentsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// DeleteDocumentRequest deletes a document.
type DeleteDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_rag_v1_rag_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

// DeleteDocumentResponse confirms deletion.
type DeleteDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentResponse) Reset() {
	*x = DeleteDocumentResponse{}
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentResponse) ProtoMessage() {}

func (x *DeleteDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_rag_v1_rag_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ReprocessDocumentRequest reprocesses an existing document.
type ReprocessDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	FileContent   []byte                 `protobuf:"bytes,2,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"` // optional new content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReprocessDocumentRequest) Reset() {
	*x = ReprocessDocumentRequest{}
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReprocessDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReprocessDocumentRequest) ProtoMessage() {}

func (x *ReprocessDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReprocessDocumentRequest.ProtoReflect.Descriptor instead.
func (*ReprocessDocumentRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_rag_v1_rag_proto_rawDescGZIP(), []int{7}
}

func (x *ReprocessDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ReprocessDocumentRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

// ReprocessDocumentResponse confirms reprocessing.
type ReprocessDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReprocessDocumentResponse) Reset() {
	*x = ReprocessDocumentResponse{}
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReprocessDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReprocessDocumentResponse) ProtoMessage() {}

func (x *ReprocessDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReprocessDocumentResponse.ProtoReflect.Descriptor instead.
func (*ReprocessDocumentResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_rag_v1_rag_proto_rawDescGZIP(), []int{8}
}

func (x *ReprocessDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// SearchRequest performs a similarity search.
type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_rag_v1_rag_proto_rawDescGZIP(), []int{9}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

// SearchResult is a single search hit.
type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	DocumentName  string                 `protobuf:"bytes,2,opt,name=document_name,json=documentName,proto3" json:"document_name,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Similarity    float64                `protobuf:"fixed64,4,opt,name=similarity,proto3" json:"similarity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_shared_proto_rag_v1_rag_proto_rawDescGZIP(), []int{10}
}

func (x *SearchResult) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *SearchResult) GetDocumentName() string {
	if x != nil {
		return x.DocumentName
	}
	return ""
}

func (x *SearchResult) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SearchResult) GetSimilarity() float64 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

// SearchResponse returns search results.
type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Results       []*SearchResult        `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_rag_v1_rag_proto_rawDescGZIP(), []int{11}
}

func (x *SearchResponse) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchResponse) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// GetStatsRequest fetches RAG statistics.
type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_rag_v1_rag_proto_rawDescGZIP(), []int{12}
}

// GetStatsResponse returns tenant RAG statistics.
type GetStatsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DocumentCount      int32                  `protobuf:"varint,1,opt,name=document_count,json=documentCount,proto3" json:"document_count,omitempty"`
	CompletedDocuments int32                  `protobuf:"varint,2,opt,name=completed_documents,json=completedDocuments,proto3" json:"completed_documents,omitempty"`
	PendingDocuments   int32                  `protobuf:"varint,3,opt,name=pending_documents,json=pendingDocuments,proto3" json:"pending_documents,omitempty"`
	EmbeddingCount     int32                  `protobuf:"varint,4,opt,name=embedding_count,json=embeddingCount,proto3" json:"embedding_count,omitempty"`
	TotalFileSizeBytes int64                  `protobuf:"varint,5,opt,name=total_file_size_bytes,json=totalFileSizeBytes,proto3" json:"total_file_size_bytes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_rag_v1_rag_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_rag_v1_rag_proto_rawDescGZIP(), []int{13}
}

func (x *GetStatsResponse) GetDocumentCount() int32 {
	if x != nil {
		return x.DocumentCount
	}
	return 0
}

func (x *GetStatsResponse) GetCompletedDocuments() int32 {
	if x != nil {
		return x.CompletedDocuments
	}
	return 0
}

func (x *GetStatsResponse) GetPendingDocuments() int32 {
	if x != nil {
		return x.PendingDocuments
	}
	return 0
}

func (x *GetStatsResponse) GetEmbeddingCount() int32 {
	if x != nil {
		return x.EmbeddingCount
	}
	return 0
}

func (x *GetStatsResponse) GetTotalFileSizeBytes() int64 {
	if x != nil {
		return x.TotalFileSizeBytes
	}
	return 0
}

var File_shared_proto_rag_v1_rag_proto protoreflect.FileDescriptor

const file_shared_proto_rag_v1_rag_proto_rawDesc = "" +
	"\n" +
	"\x1dshared/proto/rag/v1/rag.proto\x12\x06rag.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe6\x02\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tfile_type\x18\x05 \x01(\tR\bfileType\x12\x1b\n" +
	"\tfile_size\x18\x06 \x01(\x03R\bfileSize\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12/\n" +
	"\x13progress_percentage\x18\b \x01(\x05R\x12progressPercentage\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8d\x01\n" +
	"\x15UploadDocumentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\ffile_content\x18\x03 \x01(\fR\vfileContent\x12\x1b\n" +
	"\tfile_type\x18\x04 \x01(\tR\bfileType\"Q\n" +
	"\x16UploadDocumentResponse\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"G\n" +
	"\x14ListDocumentsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x8e\x01\n" +
	"\x15ListDocumentsResponse\x12.\n" +
	"\tdocuments\x18\x01 \x03(\v2\x10.rag.v1.DocumentR\tdocuments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"8\n" +
	"\x15DeleteDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"2\n" +
	"\x16DeleteDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"^\n" +
	"\x18ReprocessDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12!\n" +
	"\ffile_content\x18\x02 \x01(\fR\vfileContent\"5\n" +
	"\x19ReprocessDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\":\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\"\x88\x01\n" +
	"\fSearchResult\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12#\n" +
	"\rdocument_name\x18\x02 \x01(\tR\fdocumentName\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"similarity\x18\x04 \x01(\x01R\n" +
	"similarity\"k\n" +
	"\x0eSearchResponse\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\x12.\n" +
	"\aresults\x18\x03 \x03(\v2\x14.rag.v1.SearchResultR\aresults\"\x11\n" +
	"\x0fGetStatsRequest\"\xf3\x01\n" +
	"\x10GetStatsResponse\x12%\n" +
	"\x0edocument_count\x18\x01 \x01(\x05R\rdocumentCount\x12/\n" +
	"\x13completed_documents\x18\x02 \x01(\x05R\x12completedDocuments\x12+\n" +
	"\x11pending_documents\x18\x03 \x01(\x05R\x10pendingDocuments\x12'\n" +
	"\x0fembedding_count\x18\x04 \x01(\x05R\x0eembeddingCount\x121\n" +
	"\x15total_file_size_bytes\x18\x05 \x01(\x03R\x12totalFileSizeBytes2\xa0\x05\n" +
	"\n" +
	"RAGService\x12t\n" +
	"\x0eUploadDocument\x12\x1d.rag.v1.UploadDocumentRequest\x1a\x1e.rag.v1.UploadDocumentResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/documents/upload\x12g\n" +
	"\rListDocuments\x12\x1c.rag.v1.ListDocumentsRequest\x1a\x1d.rag.v1.ListDocumentsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/documents\x12x\n" +
	"\x0eDeleteDocument\x12\x1d.rag.v1.DeleteDocumentRequest\x1a\x1e.rag.v1.DeleteDocumentResponse\"'\x82\xd3\xe4\x93\x02!*\x1f/api/v1/documents/{document_id}\x12\x8e\x01\n" +
	"\x11ReprocessDocument\x12 .rag.v1.ReprocessDocumentRequest\x1a!.rag.v1.ReprocessDocumentResponse\"4\x82\xd3\xe4\x93\x02.:\x01*\")/api/v1/documents/{document_id}/reprocess\x12R\n" +
	"\x06Search\x12\x15.rag.v1.SearchRequest\x1a\x16.rag.v1.SearchResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/search\x12T\n" +
	"\bGetStats\x12\x17.rag.v1.GetStatsRequest\x1a\x18.rag.v1.GetStatsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/statsB3Z1sovereign-ai-compliance/shared/proto/rag/v1;ragv1b\x06proto3"

var (
	file_shared_proto_rag_v1_rag_proto_rawDescOnce sync.Once
	file_shared_proto_rag_v1_rag_proto_rawDescData []byte
)

func file_shared_proto_rag_v1_rag_proto_rawDescGZIP() []byte {
	file_shared_proto_rag_v1_rag_proto_rawDescOnce.Do(func() {
		file_shared_proto_rag_v1_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_rag_v1_rag_proto_rawDesc), len(file_shared_proto_rag_v1_rag_proto_rawDesc)))
	})
	return file_shared_proto_rag_v1_rag_proto_rawDescData
}

var file_shared_proto_rag_v1_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_shared_proto_rag_v1_rag_proto_goTypes = []any{
	(*Document)(nil),                  // 0: rag.v1.Document
	(*UploadDocumentRequest)(nil),     // 1: rag.v1.UploadDocumentRequest
	(*UploadDocumentResponse)(nil),    // 2: rag.v1.UploadDocumentResponse
	(*ListDocumentsRequest)(nil),      // 3: rag.v1.ListDocumentsRequest
	(*ListDocumentsResponse)(nil),     // 4: rag.v1.ListDocumentsResponse
	(*DeleteDocumentRequest)(nil),     // 5: rag.v1.DeleteDocumentRequest
	(*DeleteDocumentResponse)(nil),    // 6: rag.v1.DeleteDocumentResponse
	(*ReprocessDocumentRequest)(nil),  // 7: rag.v1.ReprocessDocumentRequest
	(*ReprocessDocumentResponse)(nil), // 8: rag.v1.ReprocessDocumentResponse
	(*SearchRequest)(nil),             // 9: rag.v1.SearchRequest
	(*SearchResult)(nil),              // 10: rag.v1.SearchResult
	(*SearchResponse)(nil),            // 11: rag.v1.SearchResponse
	(*GetStatsRequest)(nil),           // 12: rag.v1.GetStatsRequest
	(*GetStatsResponse)(nil),          // 13: rag.v1.GetStatsResponse
	(*timestamppb.Timestamp)(nil),     // 14: google.protobuf.Timestamp
}
var file_shared_proto_rag_v1_rag_proto_depIdxs = []int32{
	14, // 0: rag.v1.Document.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: rag.v1.Document.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: rag.v1.ListDocumentsResponse.documents:type_name -> rag.v1.Document
	10, // 3: rag.v1.SearchResponse.results:type_name -> rag.v1.SearchResult
	1,  // 4: rag.v1.RAGService.UploadDocument:input_type -> rag.v1.UploadDocumentRequest
	3,  // 5: rag.v1.RAGService.ListDocuments:input_type -> rag.v1.ListDocumentsRequest
	5,  // 6: rag.v1.RAGService.DeleteDocument:input_type -> rag.v1.DeleteDocumentRequest
	7,  // 7: rag.v1.RAGService.ReprocessDocument:input_type -> rag.v1.ReprocessDocumentRequest
	9,  // 8: rag.v1.RAGService.Search:input_type -> rag.v1.SearchRequest
	12, // 9: rag.v1.RAGService.GetStats:input_type -> rag.v1.GetStatsRequest
	2,  // 10: rag.v1.RAGService.UploadDocument:output_type -> rag.v1.UploadDocumentResponse
	4,  // 11: rag.v1.RAGService.ListDocuments:output_type -> rag.v1.ListDocumentsResponse
	6,  // 12: rag.v1.RAGService.DeleteDocument:output_type -> rag.v1.DeleteDocumentResponse
	8,  // 13: rag.v1.RAGService.ReprocessDocument:output_type -> rag.v1.ReprocessDocumentResponse
	11, // 14: rag.v1.RAGService.Search:output_type -> rag.v1.SearchResponse
	13, // 15: rag.v1.RAGService.GetStats:output_type -> rag.v1.GetStatsResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_shared_proto_rag_v1_rag_proto_init() }
func file_shared_proto_rag_v1_rag_proto_init() {
	if File_shared_proto_rag_v1_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_rag_v1_rag_proto_rawDesc), len(file_shared_proto_rag_v1_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_rag_v1_rag_proto_goTypes,
		DependencyIndexes: file_shared_proto_rag_v1_rag_proto_depIdxs,
		MessageInfos:      file_shared_proto_rag_v1_rag_proto_msgTypes,
	}.Build()
	File_shared_proto_rag_v1_rag_proto = out.File
	file_shared_proto_rag_v1_rag_proto_goTypes = nil
	file_shared_proto_rag_v1_rag_proto_depIdxs = nil
}
