// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: shared/proto/monitoring/v1/monitoring.proto

package monitoringv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MonitoringOverview provides a high-level snapshot of AI system health.
type MonitoringOverview struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HallucinationRate string                 `protobuf:"bytes,1,opt,name=hallucination_rate,json=hallucinationRate,proto3" json:"hallucination_rate,omitempty"` // e.g. "2.3%"
	AvgTtft           string                 `protobuf:"bytes,2,opt,name=avg_ttft,json=avgTtft,proto3" json:"avg_ttft,omitempty"`                               // e.g. "120ms"
	AvgTpot           string                 `protobuf:"bytes,3,opt,name=avg_tpot,json=avgTpot,proto3" json:"avg_tpot,omitempty"`                               // e.g. "45ms"
	Alert             bool                   `protobuf:"varint,4,opt,name=alert,proto3" json:"alert,omitempty"`                                                 // true if any threshold breached
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MonitoringOverview) Reset() {
	*x = MonitoringOverview{}
	mi := &file_shared_proto_monitoring_v1_monitoring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringOverview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringOverview) ProtoMessage() {}

func (x *MonitoringOverview) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_monitoring_v1_monitoring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoringOverview.ProtoReflect.Descriptor instead.
func (*MonitoringOverview) Descriptor() ([]byte, []int) {
	return file_shared_proto_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{0}
}

func (x *MonitoringOverview) GetHallucinationRate() string {
	if x != nil {
		return x.HallucinationRate
	}
	return ""
}

func (x *MonitoringOverview) GetAvgTtft() string {
	if x != nil {
		return x.AvgTtft
	}
	return ""
}

func (x *MonitoringOverview) GetAvgTpot() string {
	if x != nil {
		return x.AvgTpot
	}
	return ""
}

func (x *MonitoringOverview) GetAlert() bool {
	if x != nil {
		return x.Alert
	}
	return false
}

// HallucinationMetrics is a single time-series point for hallucination data.
type HallucinationMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          string                 `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`           // RFC3339 timestamp
	Rate          float64                `protobuf:"fixed64,2,opt,name=rate,proto3" json:"rate,omitempty"`         // hallucination rate (0.0 - 1.0)
	Bias          float64                `protobuf:"fixed64,3,opt,name=bias,proto3" json:"bias,omitempty"`         // bias score
	Toxicity      float64                `protobuf:"fixed64,4,opt,name=toxicity,proto3" json:"toxicity,omitempty"` // toxicity score
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HallucinationMetrics) Reset() {
	*x = HallucinationMetrics{}
	mi := &file_shared_proto_monitoring_v1_monitoring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HallucinationMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HallucinationMetrics) ProtoMessage() {}

func (x *HallucinationMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_monitoring_v1_monitoring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HallucinationMetrics.ProtoReflect.Descriptor instead.
func (*HallucinationMetrics) Descriptor() ([]byte, []int) {
	return file_shared_proto_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{1}
}

func (x *HallucinationMetrics) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *HallucinationMetrics) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *HallucinationMetrics) GetBias() float64 {
	if x != nil {
		return x.Bias
	}
	return 0
}

func (x *HallucinationMetrics) GetToxicity() float64 {
	if x != nil {
		return x.Toxicity
	}
	return 0
}

// TokenPerformance is a single time-series point for token performance data.
type TokenPerformance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          string                 `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`   // RFC3339 timestamp
	Ttft          float64                `protobuf:"fixed64,2,opt,name=ttft,proto3" json:"ttft,omitempty"` // time to first token (ms)
	Tpot          float64                `protobuf:"fixed64,3,opt,name=tpot,proto3" json:"tpot,omitempty"` // time per output token (ms)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenPerformance) Reset() {
	*x = TokenPerformance{}
	mi := &file_shared_proto_monitoring_v1_monitoring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPerformance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPerformance) ProtoMessage() {}

func (x *TokenPerformance) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_monitoring_v1_monitoring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPerformance.ProtoReflect.Descriptor instead.
func (*TokenPerformance) Descriptor() ([]byte, []int) {
	return file_shared_proto_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{2}
}

func (x *TokenPerformance) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *TokenPerformance) GetTtft() float64 {
	if x != nil {
		return x.Ttft
	}
	return 0
}

func (x *TokenPerformance) GetTpot() float64 {
	if x != nil {
		return x.Tpot
	}
	return 0
}

// GetOverviewRequest is empty; tenant_id is passed via gRPC metadata header.
type GetOverviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOverviewRequest) Reset() {
	*x = GetOverviewRequest{}
	mi := &file_shared_proto_monitoring_v1_monitoring_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOverviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOverviewRequest) ProtoMessage() {}

func (x *GetOverviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_monitoring_v1_monitoring_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOverviewRequest.ProtoReflect.Descriptor instead.
func (*GetOverviewRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{3}
}

// GetOverviewResponse returns the current monitoring overview.
type GetOverviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Overview      *MonitoringOverview    `protobuf:"bytes,1,opt,name=overview,proto3" json:"overview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOverviewResponse) Reset() {
	*x = GetOverviewResponse{}
	mi := &file_shared_proto_monitoring_v1_monitoring_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOverviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOverviewResponse) ProtoMessage() {}

func (x *GetOverviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_monitoring_v1_monitoring_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOverviewResponse.ProtoReflect.Descriptor instead.
func (*GetOverviewResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{4}
}

func (x *GetOverviewResponse) GetOverview() *MonitoringOverview {
	if x != nil {
		return x.Overview
	}
	return nil
}

// GetHallucinationMetricsRequest supports optional time-range filtering.
type GetHallucinationMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHallucinationMetricsRequest) Reset() {
	*x = GetHallucinationMetricsRequest{}
	mi := &file_shared_proto_monitoring_v1_monitoring_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHallucinationMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHallucinationMetricsRequest) ProtoMessage() {}

func (x *GetHallucinationMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_monitoring_v1_monitoring_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHallucinationMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetHallucinationMetricsRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{5}
}

func (x *GetHallucinationMetricsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetHallucinationMetricsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// GetHallucinationMetricsResponse returns a time-series of hallucination metrics.
type GetHallucinationMetricsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Metrics       []*HallucinationMetrics `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHallucinationMetricsResponse) Reset() {
	*x = GetHallucinationMetricsResponse{}
	mi := &file_shared_proto_monitoring_v1_monitoring_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHallucinationMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHallucinationMetricsResponse) ProtoMessage() {}

func (x *GetHallucinationMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_monitoring_v1_monitoring_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHallucinationMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetHallucinationMetricsResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{6}
}

func (x *GetHallucinationMetricsResponse) GetMetrics() []*HallucinationMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// GetTokenPerformanceRequest supports optional time-range filtering.
type GetTokenPerformanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenPerformanceRequest) Reset() {
	*x = GetTokenPerformanceRequest{}
	mi := &file_shared_proto_monitoring_v1_monitoring_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenPerformanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenPerformanceRequest) ProtoMessage() {}

func (x *GetTokenPerformanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_monitoring_v1_monitoring_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenPerformanceRequest.ProtoReflect.Descriptor instead.
func (*GetTokenPerformanceRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{7}
}

func (x *GetTokenPerformanceRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetTokenPerformanceRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// GetTokenPerformanceResponse returns a time-series of token performance metrics.
type GetTokenPerformanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*TokenPerformance    `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenPerformanceResponse) Reset() {
	*x = GetTokenPerformanceResponse{}
	mi := &file_shared_proto_monitoring_v1_monitoring_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenPerformanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenPerformanceResponse) ProtoMessage() {}

func (x *GetTokenPerformanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_monitoring_v1_monitoring_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenPerformanceResponse.ProtoReflect.Descriptor instead.
func (*GetTokenPerformanceResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_monitoring_v1_monitoring_proto_rawDescGZIP(), []int{8}
}

func (x *GetTokenPerformanceResponse) GetMetrics() []*TokenPerformance {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_shared_proto_monitoring_v1_monitoring_proto protoreflect.FileDescriptor

const file_shared_proto_monitoring_v1_monitoring_proto_rawDesc = "" +
	"\n" +
	"+shared/proto/monitoring/v1/monitoring.proto\x12\rmonitoring.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8f\x01\n" +
	"\x12MonitoringOverview\x12-\n" +
	"\x12hallucination_rate\x18\x01 \x01(\tR\x11hallucinationRate\x12\x19\n" +
	"\bavg_ttft\x18\x02 \x01(\tR\aavgTtft\x12\x19\n" +
	"\bavg_tpot\x18\x03 \x01(\tR\aavgTpot\x12\x14\n" +
	"\x05alert\x18\x04 \x01(\bR\x05alert\"n\n" +
	"\x14HallucinationMetrics\x12\x12\n" +
	"\x04time\x18\x01 \x01(\tR\x04time\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x01R\x04rate\x12\x12\n" +
	"\x04bias\x18\x03 \x01(\x01R\x04bias\x12\x1a\n" +
	"\btoxicity\x18\x04 \x01(\x01R\btoxicity\"N\n" +
	"\x10TokenPerformance\x12\x12\n" +
	"\x04time\x18\x01 \x01(\tR\x04time\x12\x12\n" +
	"\x04ttft\x18\x02 \x01(\x01R\x04ttft\x12\x12\n" +
	"\x04tpot\x18\x03 \x01(\x01R\x04tpot\"\x14\n" +
	"\x12GetOverviewRequest\"T\n" +
	"\x13GetOverviewResponse\x12=\n" +
	"\boverview\x18\x01 \x01(\v2!.monitoring.v1.MonitoringOverviewR\boverview\"\x92\x01\n" +
	"\x1eGetHallucinationMetricsRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"`\n" +
	"\x1fGetHallucinationMetricsResponse\x12=\n" +
	"\ametrics\x18\x01 \x03(\v2#.monitoring.v1.HallucinationMetricsR\ametrics\"\x8e\x01\n" +
	"\x1aGetTokenPerformanceRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"X\n" +
	"\x1bGetTokenPerformanceResponse\x129\n" +
	"\ametrics\x18\x01 \x03(\v2\x1f.monitoring.v1.TokenPerformanceR\ametrics2\xd8\x03\n" +
	"\x11MonitoringService\x12y\n" +
	"\vGetOverview\x12!.monitoring.v1.GetOverviewRequest\x1a\".monitoring.v1.GetOverviewResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/monitoring/overview\x12\xaa\x01\n" +
	"\x17GetHallucinationMetrics\x12-.monitoring.v1.GetHallucinationMetricsRequest\x1a..monitoring.v1.GetHallucinationMetricsResponse\"0\x82\xd3\xe4\x93\x02*\x12(/api/v1/monitoring/hallucination-metrics\x12\x9a\x01\n" +
	"\x13GetTokenPerformance\x12).monitoring.v1.GetTokenPerformanceRequest\x1a*.monitoring.v1.GetTokenPerformanceResponse\",\x82\xd3\xe4\x93\x02&\x12$/api/v1/monitoring/token-performanceBAZ?sovereign-ai-compliance/shared/proto/monitoring/v1;monitoringv1b\x06proto3"

var (
	file_shared_proto_monitoring_v1_monitoring_proto_rawDescOnce sync.Once
	file_shared_proto_monitoring_v1_monitoring_proto_rawDescData []byte
)

func file_shared_proto_monitoring_v1_monitoring_proto_rawDescGZIP() []byte {
	file_shared_proto_monitoring_v1_monitoring_proto_rawDescOnce.Do(func() {
		file_shared_proto_monitoring_v1_monitoring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_monitoring_v1_monitoring_proto_rawDesc), len(file_shared_proto_monitoring_v1_monitoring_proto_rawDesc)))
	})
	return file_shared_proto_monitoring_v1_monitoring_proto_rawDescData
}

var file_shared_proto_monitoring_v1_monitoring_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_shared_proto_monitoring_v1_monitoring_proto_goTypes = []any{
	(*MonitoringOverview)(nil),              // 0: monitoring.v1.MonitoringOverview
	(*HallucinationMetrics)(nil),            // 1: monitoring.v1.HallucinationMetrics
	(*TokenPerformance)(nil),                // 2: monitoring.v1.TokenPerformance
	(*GetOverviewRequest)(nil),              // 3: monitoring.v1.GetOverviewRequest
	(*GetOverviewResponse)(nil),             // 4: monitoring.v1.GetOverviewResponse
	(*GetHallucinationMetricsRequest)(nil),  // 5: monitoring.v1.GetHallucinationMetricsRequest
	(*GetHallucinationMetricsResponse)(nil), // 6: monitoring.v1.GetHallucinationMetricsResponse
	(*GetTokenPerformanceRequest)(nil),      // 7: monitoring.v1.GetTokenPerformanceRequest
	(*GetTokenPerformanceResponse)(nil),     // 8: monitoring.v1.GetTokenPerformanceResponse
	(*timestamppb.Timestamp)(nil),           // 9: google.protobuf.Timestamp
}
var file_shared_proto_monitoring_v1_monitoring_proto_depIdxs = []int32{
	0,  // 0: monitoring.v1.GetOverviewResponse.overview:type_name -> monitoring.v1.MonitoringOverview
	9,  // 1: monitoring.v1.GetHallucinationMetricsRequest.start_time:type_name -> google.protobuf.Timestamp
	9,  // 2: monitoring.v1.GetHallucinationMetricsRequest.end_time:type_name -> google.protobuf.Timestamp
	1,  // 3: monitoring.v1.GetHallucinationMetricsResponse.metrics:type_name -> monitoring.v1.HallucinationMetrics
	9,  // 4: monitoring.v1.GetTokenPerformanceRequest.start_time:type_name -> google.protobuf.Timestamp
	9,  // 5: monitoring.v1.GetTokenPerformanceRequest.end_time:type_name -> google.protobuf.Timestamp
	2,  // 6: monitoring.v1.GetTokenPerformanceResponse.metrics:type_name -> monitoring.v1.TokenPerformance
	3,  // 7: monitoring.v1.MonitoringService.GetOverview:input_type -> monitoring.v1.GetOverviewRequest
	5,  // 8: monitoring.v1.MonitoringService.GetHallucinationMetrics:input_type -> monitoring.v1.GetHallucinationMetricsRequest
	7,  // 9: monitoring.v1.MonitoringService.GetTokenPerformance:input_type -> monitoring.v1.GetTokenPerformanceRequest
	4,  // 10: monitoring.v1.MonitoringService.GetOverview:output_type -> monitoring.v1.GetOverviewResponse
	6,  // 11: monitoring.v1.MonitoringService.GetHallucinationMetrics:output_type -> monitoring.v1.GetHallucinationMetricsResponse
	8,  // 12: monitoring.v1.MonitoringService.GetTokenPerformance:output_type -> monitoring.v1.GetTokenPerformanceResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_shared_proto_monitoring_v1_monitoring_proto_init() }
func file_shared_proto_monitoring_v1_monitoring_proto_init() {
	if File_shared_proto_monitoring_v1_monitoring_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_monitoring_v1_monitoring_proto_rawDesc), len(file_shared_proto_monitoring_v1_monitoring_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_monitoring_v1_monitoring_proto_goTypes,
		DependencyIndexes: file_shared_proto_monitoring_v1_monitoring_proto_depIdxs,
		MessageInfos:      file_shared_proto_monitoring_v1_monitoring_proto_msgTypes,
	}.Build()
	File_shared_proto_monitoring_v1_monitoring_proto = out.File
	file_shared_proto_monitoring_v1_monitoring_proto_goTypes = nil
	file_shared_proto_monitoring_v1_monitoring_proto_depIdxs = nil
}
