// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: shared/proto/monitoring/v1/monitoring.proto

package monitoringv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MonitoringService_GetOverview_FullMethodName             = "/monitoring.v1.MonitoringService/GetOverview"
	MonitoringService_GetHallucinationMetrics_FullMethodName = "/monitoring.v1.MonitoringService/GetHallucinationMetrics"
	MonitoringService_GetTokenPerformance_FullMethodName     = "/monitoring.v1.MonitoringService/GetTokenPerformance"
)

// MonitoringServiceClient is the client API for MonitoringService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MonitoringService exposes AI system monitoring endpoints.
type MonitoringServiceClient interface {
	GetOverview(ctx context.Context, in *GetOverviewRequest, opts ...grpc.CallOption) (*GetOverviewResponse, error)
	GetHallucinationMetrics(ctx context.Context, in *GetHallucinationMetricsRequest, opts ...grpc.CallOption) (*GetHallucinationMetricsResponse, error)
	GetTokenPerformance(ctx context.Context, in *GetTokenPerformanceRequest, opts ...grpc.CallOption) (*GetTokenPerformanceResponse, error)
}

type monitoringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitoringServiceClient(cc grpc.ClientConnInterface) MonitoringServiceClient {
	return &monitoringServiceClient{cc}
}

func (c *monitoringServiceClient) GetOverview(ctx context.Context, in *GetOverviewRequest, opts ...grpc.CallOption) (*GetOverviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOverviewResponse)
	err := c.cc.Invoke(ctx, MonitoringService_GetOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringServiceClient) GetHallucinationMetrics(ctx context.Context, in *GetHallucinationMetricsRequest, opts ...grpc.CallOption) (*GetHallucinationMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHallucinationMetricsResponse)
	err := c.cc.Invoke(ctx, MonitoringService_GetHallucinationMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringServiceClient) GetTokenPerformance(ctx context.Context, in *GetTokenPerformanceRequest, opts ...grpc.CallOption) (*GetTokenPerformanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTokenPerformanceResponse)
	err := c.cc.Invoke(ctx, MonitoringService_GetTokenPerformance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitoringServiceServer is the server API for MonitoringService service.
// All implementations must embed UnimplementedMonitoringServiceServer
// for forward compatibility.
//
// MonitoringService exposes AI system monitoring endpoints.
type MonitoringServiceServer interface {
	GetOverview(context.Context, *GetOverviewRequest) (*GetOverviewResponse, error)
	GetHallucinationMetrics(context.Context, *GetHallucinationMetricsRequest) (*GetHallucinationMetricsResponse, error)
	GetTokenPerformance(context.Context, *GetTokenPerformanceRequest) (*GetTokenPerformanceResponse, error)
	mustEmbedUnimplementedMonitoringServiceServer()
}

// UnimplementedMonitoringServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMonitoringServiceServer struct{}

func (UnimplementedMonitoringServiceServer) GetOverview(context.Context, *GetOverviewRequest) (*GetOverviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOverview not implemented")
}
func (UnimplementedMonitoringServiceServer) GetHallucinationMetrics(context.Context, *GetHallucinationMetricsRequest) (*GetHallucinationMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHallucinationMetrics not implemented")
}
func (UnimplementedMonitoringServiceServer) GetTokenPerformance(context.Context, *GetTokenPerformanceRequest) (*GetTokenPerformanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTokenPerformance not implemented")
}
func (UnimplementedMonitoringServiceServer) mustEmbedUnimplementedMonitoringServiceServer() {}
func (UnimplementedMonitoringServiceServer) testEmbeddedByValue()                           {}

// UnsafeMonitoringServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitoringServiceServer will
// result in compilation errors.
type UnsafeMonitoringServiceServer interface {
	mustEmbedUnimplementedMonitoringServiceServer()
}

func RegisterMonitoringServiceServer(s grpc.ServiceRegistrar, srv MonitoringServiceServer) {
	// If the following call pancis, it indicates UnimplementedMonitoringServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MonitoringService_ServiceDesc, srv)
}

func _MonitoringService_GetOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOverviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServiceServer).GetOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitoringService_GetOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServiceServer).GetOverview(ctx, req.(*GetOverviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitoringService_GetHallucinationMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHallucinationMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServiceServer).GetHallucinationMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitoringService_GetHallucinationMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServiceServer).GetHallucinationMetrics(ctx, req.(*GetHallucinationMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitoringService_GetTokenPerformance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenPerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServiceServer).GetTokenPerformance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonitoringService_GetTokenPerformance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServiceServer).GetTokenPerformance(ctx, req.(*GetTokenPerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MonitoringService_ServiceDesc is the grpc.ServiceDesc for MonitoringService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonitoringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitoring.v1.MonitoringService",
	HandlerType: (*MonitoringServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOverview",
			Handler:    _MonitoringService_GetOverview_Handler,
		},
		{
			MethodName: "GetHallucinationMetrics",
			Handler:    _MonitoringService_GetHallucinationMetrics_Handler,
		},
		{
			MethodName: "GetTokenPerformance",
			Handler:    _MonitoringService_GetTokenPerformance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shared/proto/monitoring/v1/monitoring.proto",
}
