// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: shared/proto/doc/v1/doc.proto

package docv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DocumentStatus represents the lifecycle state of a generated document.
type DocumentStatus int32

const (
	DocumentStatus_DOCUMENT_STATUS_UNSPECIFIED DocumentStatus = 0
	DocumentStatus_DOCUMENT_STATUS_GENERATING  DocumentStatus = 1
	DocumentStatus_DOCUMENT_STATUS_EDITING     DocumentStatus = 2
	DocumentStatus_DOCUMENT_STATUS_APPROVED    DocumentStatus = 3
	DocumentStatus_DOCUMENT_STATUS_PUBLISHED   DocumentStatus = 4
	DocumentStatus_DOCUMENT_STATUS_FAILED      DocumentStatus = 5
)

// Enum value maps for DocumentStatus.
var (
	DocumentStatus_name = map[int32]string{
		0: "DOCUMENT_STATUS_UNSPECIFIED",
		1: "DOCUMENT_STATUS_GENERATING",
		2: "DOCUMENT_STATUS_EDITING",
		3: "DOCUMENT_STATUS_APPROVED",
		4: "DOCUMENT_STATUS_PUBLISHED",
		5: "DOCUMENT_STATUS_FAILED",
	}
	DocumentStatus_value = map[string]int32{
		"DOCUMENT_STATUS_UNSPECIFIED": 0,
		"DOCUMENT_STATUS_GENERATING":  1,
		"DOCUMENT_STATUS_EDITING":     2,
		"DOCUMENT_STATUS_APPROVED":    3,
		"DOCUMENT_STATUS_PUBLISHED":   4,
		"DOCUMENT_STATUS_FAILED":      5,
	}
)

func (x DocumentStatus) Enum() *DocumentStatus {
	p := new(DocumentStatus)
	*p = x
	return p
}

func (x DocumentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_doc_v1_doc_proto_enumTypes[0].Descriptor()
}

func (DocumentStatus) Type() protoreflect.EnumType {
	return &file_shared_proto_doc_v1_doc_proto_enumTypes[0]
}

func (x DocumentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentStatus.Descriptor instead.
func (DocumentStatus) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{0}
}

// DocType represents the type of compliance document.
type DocType int32

const (
	DocType_DOC_TYPE_UNSPECIFIED DocType = 0
	DocType_DOC_TYPE_ANNEX_IV    DocType = 1
	DocType_DOC_TYPE_RISK_REPORT DocType = 2
	DocType_DOC_TYPE_COMPLIANCE  DocType = 3
)

// Enum value maps for DocType.
var (
	DocType_name = map[int32]string{
		0: "DOC_TYPE_UNSPECIFIED",
		1: "DOC_TYPE_ANNEX_IV",
		2: "DOC_TYPE_RISK_REPORT",
		3: "DOC_TYPE_COMPLIANCE",
	}
	DocType_value = map[string]int32{
		"DOC_TYPE_UNSPECIFIED": 0,
		"DOC_TYPE_ANNEX_IV":    1,
		"DOC_TYPE_RISK_REPORT": 2,
		"DOC_TYPE_COMPLIANCE":  3,
	}
)

func (x DocType) Enum() *DocType {
	p := new(DocType)
	*p = x
	return p
}

func (x DocType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocType) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_doc_v1_doc_proto_enumTypes[1].Descriptor()
}

func (DocType) Type() protoreflect.EnumType {
	return &file_shared_proto_doc_v1_doc_proto_enumTypes[1]
}

func (x DocType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocType.Descriptor instead.
func (DocType) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{1}
}

// ExportFormat represents the output format for document export.
type ExportFormat int32

const (
	ExportFormat_EXPORT_FORMAT_UNSPECIFIED ExportFormat = 0
	ExportFormat_EXPORT_FORMAT_PDF         ExportFormat = 1
	ExportFormat_EXPORT_FORMAT_DOCX        ExportFormat = 2
)

// Enum value maps for ExportFormat.
var (
	ExportFormat_name = map[int32]string{
		0: "EXPORT_FORMAT_UNSPECIFIED",
		1: "EXPORT_FORMAT_PDF",
		2: "EXPORT_FORMAT_DOCX",
	}
	ExportFormat_value = map[string]int32{
		"EXPORT_FORMAT_UNSPECIFIED": 0,
		"EXPORT_FORMAT_PDF":         1,
		"EXPORT_FORMAT_DOCX":        2,
	}
)

func (x ExportFormat) Enum() *ExportFormat {
	p := new(ExportFormat)
	*p = x
	return p
}

func (x ExportFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExportFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_doc_v1_doc_proto_enumTypes[2].Descriptor()
}

func (ExportFormat) Type() protoreflect.EnumType {
	return &file_shared_proto_doc_v1_doc_proto_enumTypes[2]
}

func (x ExportFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExportFormat.Descriptor instead.
func (ExportFormat) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{2}
}

// ExportStatus represents the state of an export job.
type ExportStatus int32

const (
	ExportStatus_EXPORT_STATUS_UNSPECIFIED ExportStatus = 0
	ExportStatus_EXPORT_STATUS_PENDING     ExportStatus = 1
	ExportStatus_EXPORT_STATUS_PROCESSING  ExportStatus = 2
	ExportStatus_EXPORT_STATUS_COMPLETED   ExportStatus = 3
	ExportStatus_EXPORT_STATUS_FAILED      ExportStatus = 4
)

// Enum value maps for ExportStatus.
var (
	ExportStatus_name = map[int32]string{
		0: "EXPORT_STATUS_UNSPECIFIED",
		1: "EXPORT_STATUS_PENDING",
		2: "EXPORT_STATUS_PROCESSING",
		3: "EXPORT_STATUS_COMPLETED",
		4: "EXPORT_STATUS_FAILED",
	}
	ExportStatus_value = map[string]int32{
		"EXPORT_STATUS_UNSPECIFIED": 0,
		"EXPORT_STATUS_PENDING":     1,
		"EXPORT_STATUS_PROCESSING":  2,
		"EXPORT_STATUS_COMPLETED":   3,
		"EXPORT_STATUS_FAILED":      4,
	}
)

func (x ExportStatus) Enum() *ExportStatus {
	p := new(ExportStatus)
	*p = x
	return p
}

func (x ExportStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExportStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_doc_v1_doc_proto_enumTypes[3].Descriptor()
}

func (ExportStatus) Type() protoreflect.EnumType {
	return &file_shared_proto_doc_v1_doc_proto_enumTypes[3]
}

func (x ExportStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExportStatus.Descriptor instead.
func (ExportStatus) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{3}
}

// SubSection represents a document subsection.
type SubSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Order         int32                  `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubSection) Reset() {
	*x = SubSection{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubSection) ProtoMessage() {}

func (x *SubSection) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubSection.ProtoReflect.Descriptor instead.
func (*SubSection) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{0}
}

func (x *SubSection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubSection) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SubSection) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SubSection) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

// Section represents a document section.
type Section struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Order         int32                  `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	Subsections   []*SubSection          `protobuf:"bytes,5,rep,name=subsections,proto3" json:"subsections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Section) Reset() {
	*x = Section{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Section) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Section) ProtoMessage() {}

func (x *Section) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Section.ProtoReflect.Descriptor instead.
func (*Section) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{1}
}

func (x *Section) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Section) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Section) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Section) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *Section) GetSubsections() []*SubSection {
	if x != nil {
		return x.Subsections
	}
	return nil
}

// DocumentContent holds the structured document with sections and metadata.
type DocumentContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sections      []*Section             `protobuf:"bytes,1,rep,name=sections,proto3" json:"sections,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentContent) Reset() {
	*x = DocumentContent{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentContent) ProtoMessage() {}

func (x *DocumentContent) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentContent.ProtoReflect.Descriptor instead.
func (*DocumentContent) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{2}
}

func (x *DocumentContent) GetSections() []*Section {
	if x != nil {
		return x.Sections
	}
	return nil
}

func (x *DocumentContent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// GeneratedDocument represents a compliance document.
type GeneratedDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AiSystemId    string                 `protobuf:"bytes,3,opt,name=ai_system_id,json=aiSystemId,proto3" json:"ai_system_id,omitempty"`
	DocType       DocType                `protobuf:"varint,4,opt,name=doc_type,json=docType,proto3,enum=doc.v1.DocType" json:"doc_type,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Content       *DocumentContent       `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Version       int32                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	Status        DocumentStatus         `protobuf:"varint,8,opt,name=status,proto3,enum=doc.v1.DocumentStatus" json:"status,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratedDocument) Reset() {
	*x = GeneratedDocument{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedDocument) ProtoMessage() {}

func (x *GeneratedDocument) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedDocument.ProtoReflect.Descriptor instead.
func (*GeneratedDocument) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{3}
}

func (x *GeneratedDocument) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GeneratedDocument) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GeneratedDocument) GetAiSystemId() string {
	if x != nil {
		return x.AiSystemId
	}
	return ""
}

func (x *GeneratedDocument) GetDocType() DocType {
	if x != nil {
		return x.DocType
	}
	return DocType_DOC_TYPE_UNSPECIFIED
}

func (x *GeneratedDocument) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GeneratedDocument) GetContent() *DocumentContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GeneratedDocument) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GeneratedDocument) GetStatus() DocumentStatus {
	if x != nil {
		return x.Status
	}
	return DocumentStatus_DOCUMENT_STATUS_UNSPECIFIED
}

func (x *GeneratedDocument) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *GeneratedDocument) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GeneratedDocument) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// DocumentSummary is a lightweight summary for listing documents.
type DocumentSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AiSystemId    string                 `protobuf:"bytes,2,opt,name=ai_system_id,json=aiSystemId,proto3" json:"ai_system_id,omitempty"`
	DocType       DocType                `protobuf:"varint,3,opt,name=doc_type,json=docType,proto3,enum=doc.v1.DocType" json:"doc_type,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Status        DocumentStatus         `protobuf:"varint,6,opt,name=status,proto3,enum=doc.v1.DocumentStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentSummary) Reset() {
	*x = DocumentSummary{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentSummary) ProtoMessage() {}

func (x *DocumentSummary) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentSummary.ProtoReflect.Descriptor instead.
func (*DocumentSummary) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{4}
}

func (x *DocumentSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentSummary) GetAiSystemId() string {
	if x != nil {
		return x.AiSystemId
	}
	return ""
}

func (x *DocumentSummary) GetDocType() DocType {
	if x != nil {
		return x.DocType
	}
	return DocType_DOC_TYPE_UNSPECIFIED
}

func (x *DocumentSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocumentSummary) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DocumentSummary) GetStatus() DocumentStatus {
	if x != nil {
		return x.Status
	}
	return DocumentStatus_DOCUMENT_STATUS_UNSPECIFIED
}

func (x *DocumentSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DocumentSummary) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// DocumentVersion tracks version history for a document.
type DocumentVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,3,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	VersionNumber int32                  `protobuf:"varint,4,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	Content       *DocumentContent       `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ChangeSummary string                 `protobuf:"bytes,8,opt,name=change_summary,json=changeSummary,proto3" json:"change_summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentVersion) Reset() {
	*x = DocumentVersion{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentVersion) ProtoMessage() {}

func (x *DocumentVersion) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentVersion.ProtoReflect.Descriptor instead.
func (*DocumentVersion) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{5}
}

func (x *DocumentVersion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentVersion) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DocumentVersion) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentVersion) GetVersionNumber() int32 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

func (x *DocumentVersion) GetContent() *DocumentContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *DocumentVersion) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *DocumentVersion) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DocumentVersion) GetChangeSummary() string {
	if x != nil {
		return x.ChangeSummary
	}
	return ""
}

// ExportJob represents an async document export operation.
type ExportJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,3,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Format        ExportFormat           `protobuf:"varint,4,opt,name=format,proto3,enum=doc.v1.ExportFormat" json:"format,omitempty"`
	Status        ExportStatus           `protobuf:"varint,5,opt,name=status,proto3,enum=doc.v1.ExportStatus" json:"status,omitempty"`
	FilePath      string                 `protobuf:"bytes,6,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileSize      int64                  `protobuf:"varint,7,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportJob) Reset() {
	*x = ExportJob{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportJob) ProtoMessage() {}

func (x *ExportJob) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportJob.ProtoReflect.Descriptor instead.
func (*ExportJob) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{6}
}

func (x *ExportJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExportJob) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ExportJob) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ExportJob) GetFormat() ExportFormat {
	if x != nil {
		return x.Format
	}
	return ExportFormat_EXPORT_FORMAT_UNSPECIFIED
}

func (x *ExportJob) GetStatus() ExportStatus {
	if x != nil {
		return x.Status
	}
	return ExportStatus_EXPORT_STATUS_UNSPECIFIED
}

func (x *ExportJob) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ExportJob) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *ExportJob) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ExportJob) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ExportJob) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ExportJob) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// GenerateDocumentRequest triggers document generation.
type GenerateDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AiSystemId    string                 `protobuf:"bytes,1,opt,name=ai_system_id,json=aiSystemId,proto3" json:"ai_system_id,omitempty"`
	DocType       DocType                `protobuf:"varint,2,opt,name=doc_type,json=docType,proto3,enum=doc.v1.DocType" json:"doc_type,omitempty"`
	AuditJobId    string                 `protobuf:"bytes,3,opt,name=audit_job_id,json=auditJobId,proto3" json:"audit_job_id,omitempty"` // optional
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Options       map[string]string      `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDocumentRequest) Reset() {
	*x = GenerateDocumentRequest{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDocumentRequest) ProtoMessage() {}

func (x *GenerateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDocumentRequest.ProtoReflect.Descriptor instead.
func (*GenerateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateDocumentRequest) GetAiSystemId() string {
	if x != nil {
		return x.AiSystemId
	}
	return ""
}

func (x *GenerateDocumentRequest) GetDocType() DocType {
	if x != nil {
		return x.DocType
	}
	return DocType_DOC_TYPE_UNSPECIFIED
}

func (x *GenerateDocumentRequest) GetAuditJobId() string {
	if x != nil {
		return x.AuditJobId
	}
	return ""
}

func (x *GenerateDocumentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GenerateDocumentRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

// GenerateDocumentResponse confirms generation was triggered.
type GenerateDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Status        DocumentStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=doc.v1.DocumentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDocumentResponse) Reset() {
	*x = GenerateDocumentResponse{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDocumentResponse) ProtoMessage() {}

func (x *GenerateDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDocumentResponse.ProtoReflect.Descriptor instead.
func (*GenerateDocumentResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{8}
}

func (x *GenerateDocumentResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *GenerateDocumentResponse) GetStatus() DocumentStatus {
	if x != nil {
		return x.Status
	}
	return DocumentStatus_DOCUMENT_STATUS_UNSPECIFIED
}

// ListDocumentsRequest lists documents with filtering.
type ListDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AiSystemId    string                 `protobuf:"bytes,1,opt,name=ai_system_id,json=aiSystemId,proto3" json:"ai_system_id,omitempty"` // optional filter
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                             // optional filter by status name
	DocType       string                 `protobuf:"bytes,3,opt,name=doc_type,json=docType,proto3" json:"doc_type,omitempty"`            // optional filter by doc type name
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsRequest) Reset() {
	*x = ListDocumentsRequest{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsRequest) ProtoMessage() {}

func (x *ListDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{9}
}

func (x *ListDocumentsRequest) GetAiSystemId() string {
	if x != nil {
		return x.AiSystemId
	}
	return ""
}

func (x *ListDocumentsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListDocumentsRequest) GetDocType() string {
	if x != nil {
		return x.DocType
	}
	return ""
}

func (x *ListDocumentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDocumentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListDocumentsResponse returns paginated documents.
type ListDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DocumentSummary     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Pages         int32                  `protobuf:"varint,4,opt,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsResponse) Reset() {
	*x = ListDocumentsResponse{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsResponse) ProtoMessage() {}

func (x *ListDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{10}
}

func (x *ListDocumentsResponse) GetItems() []*DocumentSummary {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListDocumentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListDocumentsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDocumentsResponse) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

// GetDocumentRequest fetches a single document.
type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{11}
}

func (x *GetDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

// GetDocumentResponse returns the full document.
type GetDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *GeneratedDocument     `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentResponse) Reset() {
	*x = GetDocumentResponse{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentResponse) ProtoMessage() {}

func (x *GetDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{12}
}

func (x *GetDocumentResponse) GetDocument() *GeneratedDocument {
	if x != nil {
		return x.Document
	}
	return nil
}

// UpdateDocumentRequest updates document content.
type UpdateDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Content       *DocumentContent       `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,3,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocumentRequest) Reset() {
	*x = UpdateDocumentRequest{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentRequest) ProtoMessage() {}

func (x *UpdateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentRequest.ProtoReflect.Descriptor instead.
func (*UpdateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *UpdateDocumentRequest) GetContent() *DocumentContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UpdateDocumentRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

// UpdateDocumentResponse returns the updated document.
type UpdateDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *GeneratedDocument     `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocumentResponse) Reset() {
	*x = UpdateDocumentResponse{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentResponse) ProtoMessage() {}

func (x *UpdateDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentResponse.ProtoReflect.Descriptor instead.
func (*UpdateDocumentResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateDocumentResponse) GetDocument() *GeneratedDocument {
	if x != nil {
		return x.Document
	}
	return nil
}

// UpdateDocumentStatusRequest updates the document status.
type UpdateDocumentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Status        DocumentStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=doc.v1.DocumentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocumentStatusRequest) Reset() {
	*x = UpdateDocumentStatusRequest{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentStatusRequest) ProtoMessage() {}

func (x *UpdateDocumentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateDocumentStatusRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateDocumentStatusRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *UpdateDocumentStatusRequest) GetStatus() DocumentStatus {
	if x != nil {
		return x.Status
	}
	return DocumentStatus_DOCUMENT_STATUS_UNSPECIFIED
}

// UpdateDocumentStatusResponse confirms the status update.
type UpdateDocumentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Status        DocumentStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=doc.v1.DocumentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocumentStatusResponse) Reset() {
	*x = UpdateDocumentStatusResponse{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentStatusResponse) ProtoMessage() {}

func (x *UpdateDocumentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateDocumentStatusResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateDocumentStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateDocumentStatusResponse) GetStatus() DocumentStatus {
	if x != nil {
		return x.Status
	}
	return DocumentStatus_DOCUMENT_STATUS_UNSPECIFIED
}

// ListVersionsRequest lists versions for a document.
type ListVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsRequest) Reset() {
	*x = ListVersionsRequest{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsRequest) ProtoMessage() {}

func (x *ListVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListVersionsRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{17}
}

func (x *ListVersionsRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ListVersionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListVersionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListVersionsResponse returns paginated versions.
type ListVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DocumentVersion     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Pages         int32                  `protobuf:"varint,4,opt,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsResponse) Reset() {
	*x = ListVersionsResponse{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsResponse) ProtoMessage() {}

func (x *ListVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListVersionsResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{18}
}

func (x *ListVersionsResponse) GetItems() []*DocumentVersion {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListVersionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListVersionsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListVersionsResponse) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

// RollbackVersionRequest rolls back to a specific version.
type RollbackVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	VersionNumber int32                  `protobuf:"varint,2,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackVersionRequest) Reset() {
	*x = RollbackVersionRequest{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackVersionRequest) ProtoMessage() {}

func (x *RollbackVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackVersionRequest.ProtoReflect.Descriptor instead.
func (*RollbackVersionRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{19}
}

func (x *RollbackVersionRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *RollbackVersionRequest) GetVersionNumber() int32 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

// RollbackVersionResponse returns the document after rollback.
type RollbackVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *GeneratedDocument     `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackVersionResponse) Reset() {
	*x = RollbackVersionResponse{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackVersionResponse) ProtoMessage() {}

func (x *RollbackVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackVersionResponse.ProtoReflect.Descriptor instead.
func (*RollbackVersionResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{20}
}

func (x *RollbackVersionResponse) GetDocument() *GeneratedDocument {
	if x != nil {
		return x.Document
	}
	return nil
}

// CreateExportJobRequest creates an export job.
type CreateExportJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Format        ExportFormat           `protobuf:"varint,2,opt,name=format,proto3,enum=doc.v1.ExportFormat" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExportJobRequest) Reset() {
	*x = CreateExportJobRequest{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExportJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExportJobRequest) ProtoMessage() {}

func (x *CreateExportJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExportJobRequest.ProtoReflect.Descriptor instead.
func (*CreateExportJobRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{21}
}

func (x *CreateExportJobRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *CreateExportJobRequest) GetFormat() ExportFormat {
	if x != nil {
		return x.Format
	}
	return ExportFormat_EXPORT_FORMAT_UNSPECIFIED
}

// CreateExportJobResponse confirms export job creation.
type CreateExportJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        ExportStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=doc.v1.ExportStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExportJobResponse) Reset() {
	*x = CreateExportJobResponse{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExportJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExportJobResponse) ProtoMessage() {}

func (x *CreateExportJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExportJobResponse.ProtoReflect.Descriptor instead.
func (*CreateExportJobResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{22}
}

func (x *CreateExportJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CreateExportJobResponse) GetStatus() ExportStatus {
	if x != nil {
		return x.Status
	}
	return ExportStatus_EXPORT_STATUS_UNSPECIFIED
}

// GetExportJobRequest fetches an export job status.
type GetExportJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExportJobRequest) Reset() {
	*x = GetExportJobRequest{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExportJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExportJobRequest) ProtoMessage() {}

func (x *GetExportJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExportJobRequest.ProtoReflect.Descriptor instead.
func (*GetExportJobRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{23}
}

func (x *GetExportJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// GetExportJobResponse returns export job details.
type GetExportJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *ExportJob             `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExportJobResponse) Reset() {
	*x = GetExportJobResponse{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExportJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExportJobResponse) ProtoMessage() {}

func (x *GetExportJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExportJobResponse.ProtoReflect.Descriptor instead.
func (*GetExportJobResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{24}
}

func (x *GetExportJobResponse) GetJob() *ExportJob {
	if x != nil {
		return x.Job
	}
	return nil
}

// DownloadExportRequest downloads a completed export.
type DownloadExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadExportRequest) Reset() {
	*x = DownloadExportRequest{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadExportRequest) ProtoMessage() {}

func (x *DownloadExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadExportRequest.ProtoReflect.Descriptor instead.
func (*DownloadExportRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{25}
}

func (x *DownloadExportRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// DownloadExportResponse returns the exported file.
type DownloadExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadExportResponse) Reset() {
	*x = DownloadExportResponse{}
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadExportResponse) ProtoMessage() {}

func (x *DownloadExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_doc_v1_doc_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadExportResponse.ProtoReflect.Descriptor instead.
func (*DownloadExportResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_doc_v1_doc_proto_rawDescGZIP(), []int{26}
}

func (x *DownloadExportResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *DownloadExportResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *DownloadExportResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_shared_proto_doc_v1_doc_proto protoreflect.FileDescriptor

const file_shared_proto_doc_v1_doc_proto_rawDesc = "" +
	"\n" +
	"\x1dshared/proto/doc/v1/doc.proto\x12\x06doc.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"b\n" +
	"\n" +
	"SubSection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x14\n" +
	"\x05order\x18\x04 \x01(\x05R\x05order\"\x95\x01\n" +
	"\aSection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x14\n" +
	"\x05order\x18\x04 \x01(\x05R\x05order\x124\n" +
	"\vsubsections\x18\x05 \x03(\v2\x12.doc.v1.SubSectionR\vsubsections\"\xbe\x01\n" +
	"\x0fDocumentContent\x12+\n" +
	"\bsections\x18\x01 \x03(\v2\x0f.doc.v1.SectionR\bsections\x12A\n" +
	"\bmetadata\x18\x02 \x03(\v2%.doc.v1.DocumentContent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x03\n" +
	"\x11GeneratedDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12 \n" +
	"\fai_system_id\x18\x03 \x01(\tR\n" +
	"aiSystemId\x12*\n" +
	"\bdoc_type\x18\x04 \x01(\x0e2\x0f.doc.v1.DocTypeR\adocType\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x121\n" +
	"\acontent\x18\x06 \x01(\v2\x17.doc.v1.DocumentContentR\acontent\x12\x18\n" +
	"\aversion\x18\a \x01(\x05R\aversion\x12.\n" +
	"\x06status\x18\b \x01(\x0e2\x16.doc.v1.DocumentStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc5\x02\n" +
	"\x0fDocumentSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\fai_system_id\x18\x02 \x01(\tR\n" +
	"aiSystemId\x12*\n" +
	"\bdoc_type\x18\x03 \x01(\x0e2\x0f.doc.v1.DocTypeR\adocType\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\x12.\n" +
	"\x06status\x18\x06 \x01(\x0e2\x16.doc.v1.DocumentStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xba\x02\n" +
	"\x0fDocumentVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1f\n" +
	"\vdocument_id\x18\x03 \x01(\tR\n" +
	"documentId\x12%\n" +
	"\x0eversion_number\x18\x04 \x01(\x05R\rversionNumber\x121\n" +
	"\acontent\x18\x05 \x01(\v2\x17.doc.v1.DocumentContentR\acontent\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12%\n" +
	"\x0echange_summary\x18\b \x01(\tR\rchangeSummary\"\xad\x03\n" +
	"\tExportJob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1f\n" +
	"\vdocument_id\x18\x03 \x01(\tR\n" +
	"documentId\x12,\n" +
	"\x06format\x18\x04 \x01(\x0e2\x14.doc.v1.ExportFormatR\x06format\x12,\n" +
	"\x06status\x18\x05 \x01(\x0e2\x14.doc.v1.ExportStatusR\x06status\x12\x1b\n" +
	"\tfile_path\x18\x06 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_size\x18\a \x01(\x03R\bfileSize\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fcompleted_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xa3\x02\n" +
	"\x17GenerateDocumentRequest\x12 \n" +
	"\fai_system_id\x18\x01 \x01(\tR\n" +
	"aiSystemId\x12*\n" +
	"\bdoc_type\x18\x02 \x01(\x0e2\x0f.doc.v1.DocTypeR\adocType\x12 \n" +
	"\faudit_job_id\x18\x03 \x01(\tR\n" +
	"auditJobId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12F\n" +
	"\aoptions\x18\x05 \x03(\v2,.doc.v1.GenerateDocumentRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"k\n" +
	"\x18GenerateDocumentResponse\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.doc.v1.DocumentStatusR\x06status\"\x9c\x01\n" +
	"\x14ListDocumentsRequest\x12 \n" +
	"\fai_system_id\x18\x01 \x01(\tR\n" +
	"aiSystemId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x19\n" +
	"\bdoc_type\x18\x03 \x01(\tR\adocType\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"\x86\x01\n" +
	"\x15ListDocumentsResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.doc.v1.DocumentSummaryR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05pages\x18\x04 \x01(\x05R\x05pages\"5\n" +
	"\x12GetDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"L\n" +
	"\x13GetDocumentResponse\x125\n" +
	"\bdocument\x18\x01 \x01(\v2\x19.doc.v1.GeneratedDocumentR\bdocument\"\x8a\x01\n" +
	"\x15UpdateDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x121\n" +
	"\acontent\x18\x02 \x01(\v2\x17.doc.v1.DocumentContentR\acontent\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x03 \x01(\tR\tupdatedBy\"O\n" +
	"\x16UpdateDocumentResponse\x125\n" +
	"\bdocument\x18\x01 \x01(\v2\x19.doc.v1.GeneratedDocumentR\bdocument\"n\n" +
	"\x1bUpdateDocumentStatusRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.doc.v1.DocumentStatusR\x06status\"h\n" +
	"\x1cUpdateDocumentStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.doc.v1.DocumentStatusR\x06status\"g\n" +
	"\x13ListVersionsRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x85\x01\n" +
	"\x14ListVersionsResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.doc.v1.DocumentVersionR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05pages\x18\x04 \x01(\x05R\x05pages\"`\n" +
	"\x16RollbackVersionRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12%\n" +
	"\x0eversion_number\x18\x02 \x01(\x05R\rversionNumber\"P\n" +
	"\x17RollbackVersionResponse\x125\n" +
	"\bdocument\x18\x01 \x01(\v2\x19.doc.v1.GeneratedDocumentR\bdocument\"g\n" +
	"\x16CreateExportJobRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12,\n" +
	"\x06format\x18\x02 \x01(\x0e2\x14.doc.v1.ExportFormatR\x06format\"^\n" +
	"\x17CreateExportJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.doc.v1.ExportStatusR\x06status\",\n" +
	"\x13GetExportJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\";\n" +
	"\x14GetExportJobResponse\x12#\n" +
	"\x03job\x18\x01 \x01(\v2\x11.doc.v1.ExportJobR\x03job\".\n" +
	"\x15DownloadExportRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"k\n" +
	"\x16DownloadExportResponse\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data*\xc7\x01\n" +
	"\x0eDocumentStatus\x12\x1f\n" +
	"\x1bDOCUMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aDOCUMENT_STATUS_GENERATING\x10\x01\x12\x1b\n" +
	"\x17DOCUMENT_STATUS_EDITING\x10\x02\x12\x1c\n" +
	"\x18DOCUMENT_STATUS_APPROVED\x10\x03\x12\x1d\n" +
	"\x19DOCUMENT_STATUS_PUBLISHED\x10\x04\x12\x1a\n" +
	"\x16DOCUMENT_STATUS_FAILED\x10\x05*m\n" +
	"\aDocType\x12\x18\n" +
	"\x14DOC_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DOC_TYPE_ANNEX_IV\x10\x01\x12\x18\n" +
	"\x14DOC_TYPE_RISK_REPORT\x10\x02\x12\x17\n" +
	"\x13DOC_TYPE_COMPLIANCE\x10\x03*\\\n" +
	"\fExportFormat\x12\x1d\n" +
	"\x19EXPORT_FORMAT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EXPORT_FORMAT_PDF\x10\x01\x12\x16\n" +
	"\x12EXPORT_FORMAT_DOCX\x10\x02*\x9d\x01\n" +
	"\fExportStatus\x12\x1d\n" +
	"\x19EXPORT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EXPORT_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18EXPORT_STATUS_PROCESSING\x10\x02\x12\x1b\n" +
	"\x17EXPORT_STATUS_COMPLETED\x10\x03\x12\x18\n" +
	"\x14EXPORT_STATUS_FAILED\x10\x042\xa0\t\n" +
	"\n" +
	"DocService\x12q\n" +
	"\rListDocuments\x12\x1c.doc.v1.ListDocumentsRequest\x1a\x1d.doc.v1.ListDocumentsResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/generated-documents\x12}\n" +
	"\x10GenerateDocument\x12\x1f.doc.v1.GenerateDocumentRequest\x1a .doc.v1.GenerateDocumentResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/generated-documents\x12y\n" +
	"\vGetDocument\x12\x1a.doc.v1.GetDocumentRequest\x1a\x1b.doc.v1.GetDocumentResponse\"1\x82\xd3\xe4\x93\x02+\x12)/api/v1/generated-documents/{document_id}\x12\x85\x01\n" +
	"\x0eUpdateDocument\x12\x1d.doc.v1.UpdateDocumentRequest\x1a\x1e.doc.v1.UpdateDocumentResponse\"4\x82\xd3\xe4\x93\x02.:\x01*\x1a)/api/v1/generated-documents/{document_id}\x12\x85\x01\n" +
	"\fListVersions\x12\x1b.doc.v1.ListVersionsRequest\x1a\x1c.doc.v1.ListVersionsResponse\":\x82\xd3\xe4\x93\x024\x122/api/v1/generated-documents/{document_id}/versions\x12\x91\x01\n" +
	"\x0fRollbackVersion\x12\x1e.doc.v1.RollbackVersionRequest\x1a\x1f.doc.v1.RollbackVersionResponse\"=\x82\xd3\xe4\x93\x027:\x01*\"2/api/v1/generated-documents/{document_id}/rollback\x12\x8f\x01\n" +
	"\x0fCreateExportJob\x12\x1e.doc.v1.CreateExportJobRequest\x1a\x1f.doc.v1.CreateExportJobResponse\";\x82\xd3\xe4\x93\x025:\x01*\"0/api/v1/generated-documents/{document_id}/export\x12o\n" +
	"\fGetExportJob\x12\x1b.doc.v1.GetExportJobRequest\x1a\x1c.doc.v1.GetExportJobResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/export-jobs/{job_id}\x12~\n" +
	"\x0eDownloadExport\x12\x1d.doc.v1.DownloadExportRequest\x1a\x1e.doc.v1.DownloadExportResponse\"-\x82\xd3\xe4\x93\x02'\x12%/api/v1/export-jobs/{job_id}/downloadB3Z1sovereign-ai-compliance/shared/proto/doc/v1;docv1b\x06proto3"

var (
	file_shared_proto_doc_v1_doc_proto_rawDescOnce sync.Once
	file_shared_proto_doc_v1_doc_proto_rawDescData []byte
)

func file_shared_proto_doc_v1_doc_proto_rawDescGZIP() []byte {
	file_shared_proto_doc_v1_doc_proto_rawDescOnce.Do(func() {
		file_shared_proto_doc_v1_doc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_doc_v1_doc_proto_rawDesc), len(file_shared_proto_doc_v1_doc_proto_rawDesc)))
	})
	return file_shared_proto_doc_v1_doc_proto_rawDescData
}

var file_shared_proto_doc_v1_doc_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_shared_proto_doc_v1_doc_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_shared_proto_doc_v1_doc_proto_goTypes = []any{
	(DocumentStatus)(0),                  // 0: doc.v1.DocumentStatus
	(DocType)(0),                         // 1: doc.v1.DocType
	(ExportFormat)(0),                    // 2: doc.v1.ExportFormat
	(ExportStatus)(0),                    // 3: doc.v1.ExportStatus
	(*SubSection)(nil),                   // 4: doc.v1.SubSection
	(*Section)(nil),                      // 5: doc.v1.Section
	(*DocumentContent)(nil),              // 6: doc.v1.DocumentContent
	(*GeneratedDocument)(nil),            // 7: doc.v1.GeneratedDocument
	(*DocumentSummary)(nil),              // 8: doc.v1.DocumentSummary
	(*DocumentVersion)(nil),              // 9: doc.v1.DocumentVersion
	(*ExportJob)(nil),                    // 10: doc.v1.ExportJob
	(*GenerateDocumentRequest)(nil),      // 11: doc.v1.GenerateDocumentRequest
	(*GenerateDocumentResponse)(nil),     // 12: doc.v1.GenerateDocumentResponse
	(*ListDocumentsRequest)(nil),         // 13: doc.v1.ListDocumentsRequest
	(*ListDocumentsResponse)(nil),        // 14: doc.v1.ListDocumentsResponse
	(*GetDocumentRequest)(nil),           // 15: doc.v1.GetDocumentRequest
	(*GetDocumentResponse)(nil),          // 16: doc.v1.GetDocumentResponse
	(*UpdateDocumentRequest)(nil),        // 17: doc.v1.UpdateDocumentRequest
	(*UpdateDocumentResponse)(nil),       // 18: doc.v1.UpdateDocumentResponse
	(*UpdateDocumentStatusRequest)(nil),  // 19: doc.v1.UpdateDocumentStatusRequest
	(*UpdateDocumentStatusResponse)(nil), // 20: doc.v1.UpdateDocumentStatusResponse
	(*ListVersionsRequest)(nil),          // 21: doc.v1.ListVersionsRequest
	(*ListVersionsResponse)(nil),         // 22: doc.v1.ListVersionsResponse
	(*RollbackVersionRequest)(nil),       // 23: doc.v1.RollbackVersionRequest
	(*RollbackVersionResponse)(nil),      // 24: doc.v1.RollbackVersionResponse
	(*CreateExportJobRequest)(nil),       // 25: doc.v1.CreateExportJobRequest
	(*CreateExportJobResponse)(nil),      // 26: doc.v1.CreateExportJobResponse
	(*GetExportJobRequest)(nil),          // 27: doc.v1.GetExportJobRequest
	(*GetExportJobResponse)(nil),         // 28: doc.v1.GetExportJobResponse
	(*DownloadExportRequest)(nil),        // 29: doc.v1.DownloadExportRequest
	(*DownloadExportResponse)(nil),       // 30: doc.v1.DownloadExportResponse
	nil,                                  // 31: doc.v1.DocumentContent.MetadataEntry
	nil,                                  // 32: doc.v1.GenerateDocumentRequest.OptionsEntry
	(*timestamppb.Timestamp)(nil),        // 33: google.protobuf.Timestamp
}
var file_shared_proto_doc_v1_doc_proto_depIdxs = []int32{
	4,  // 0: doc.v1.Section.subsections:type_name -> doc.v1.SubSection
	5,  // 1: doc.v1.DocumentContent.sections:type_name -> doc.v1.Section
	31, // 2: doc.v1.DocumentContent.metadata:type_name -> doc.v1.DocumentContent.MetadataEntry
	1,  // 3: doc.v1.GeneratedDocument.doc_type:type_name -> doc.v1.DocType
	6,  // 4: doc.v1.GeneratedDocument.content:type_name -> doc.v1.DocumentContent
	0,  // 5: doc.v1.GeneratedDocument.status:type_name -> doc.v1.DocumentStatus
	33, // 6: doc.v1.GeneratedDocument.created_at:type_name -> google.protobuf.Timestamp
	33, // 7: doc.v1.GeneratedDocument.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 8: doc.v1.DocumentSummary.doc_type:type_name -> doc.v1.DocType
	0,  // 9: doc.v1.DocumentSummary.status:type_name -> doc.v1.DocumentStatus
	33, // 10: doc.v1.DocumentSummary.created_at:type_name -> google.protobuf.Timestamp
	33, // 11: doc.v1.DocumentSummary.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 12: doc.v1.DocumentVersion.content:type_name -> doc.v1.DocumentContent
	33, // 13: doc.v1.DocumentVersion.created_at:type_name -> google.protobuf.Timestamp
	2,  // 14: doc.v1.ExportJob.format:type_name -> doc.v1.ExportFormat
	3,  // 15: doc.v1.ExportJob.status:type_name -> doc.v1.ExportStatus
	33, // 16: doc.v1.ExportJob.created_at:type_name -> google.protobuf.Timestamp
	33, // 17: doc.v1.ExportJob.completed_at:type_name -> google.protobuf.Timestamp
	1,  // 18: doc.v1.GenerateDocumentRequest.doc_type:type_name -> doc.v1.DocType
	32, // 19: doc.v1.GenerateDocumentRequest.options:type_name -> doc.v1.GenerateDocumentRequest.OptionsEntry
	0,  // 20: doc.v1.GenerateDocumentResponse.status:type_name -> doc.v1.DocumentStatus
	8,  // 21: doc.v1.ListDocumentsResponse.items:type_name -> doc.v1.DocumentSummary
	7,  // 22: doc.v1.GetDocumentResponse.document:type_name -> doc.v1.GeneratedDocument
	6,  // 23: doc.v1.UpdateDocumentRequest.content:type_name -> doc.v1.DocumentContent
	7,  // 24: doc.v1.UpdateDocumentResponse.document:type_name -> doc.v1.GeneratedDocument
	0,  // 25: doc.v1.UpdateDocumentStatusRequest.status:type_name -> doc.v1.DocumentStatus
	0,  // 26: doc.v1.UpdateDocumentStatusResponse.status:type_name -> doc.v1.DocumentStatus
	9,  // 27: doc.v1.ListVersionsResponse.items:type_name -> doc.v1.DocumentVersion
	7,  // 28: doc.v1.RollbackVersionResponse.document:type_name -> doc.v1.GeneratedDocument
	2,  // 29: doc.v1.CreateExportJobRequest.format:type_name -> doc.v1.ExportFormat
	3,  // 30: doc.v1.CreateExportJobResponse.status:type_name -> doc.v1.ExportStatus
	10, // 31: doc.v1.GetExportJobResponse.job:type_name -> doc.v1.ExportJob
	13, // 32: doc.v1.DocService.ListDocuments:input_type -> doc.v1.ListDocumentsRequest
	11, // 33: doc.v1.DocService.GenerateDocument:input_type -> doc.v1.GenerateDocumentRequest
	15, // 34: doc.v1.DocService.GetDocument:input_type -> doc.v1.GetDocumentRequest
	17, // 35: doc.v1.DocService.UpdateDocument:input_type -> doc.v1.UpdateDocumentRequest
	21, // 36: doc.v1.DocService.ListVersions:input_type -> doc.v1.ListVersionsRequest
	23, // 37: doc.v1.DocService.RollbackVersion:input_type -> doc.v1.RollbackVersionRequest
	25, // 38: doc.v1.DocService.CreateExportJob:input_type -> doc.v1.CreateExportJobRequest
	27, // 39: doc.v1.DocService.GetExportJob:input_type -> doc.v1.GetExportJobRequest
	29, // 40: doc.v1.DocService.DownloadExport:input_type -> doc.v1.DownloadExportRequest
	14, // 41: doc.v1.DocService.ListDocuments:output_type -> doc.v1.ListDocumentsResponse
	12, // 42: doc.v1.DocService.GenerateDocument:output_type -> doc.v1.GenerateDocumentResponse
	16, // 43: doc.v1.DocService.GetDocument:output_type -> doc.v1.GetDocumentResponse
	18, // 44: doc.v1.DocService.UpdateDocument:output_type -> doc.v1.UpdateDocumentResponse
	22, // 45: doc.v1.DocService.ListVersions:output_type -> doc.v1.ListVersionsResponse
	24, // 46: doc.v1.DocService.RollbackVersion:output_type -> doc.v1.RollbackVersionResponse
	26, // 47: doc.v1.DocService.CreateExportJob:output_type -> doc.v1.CreateExportJobResponse
	28, // 48: doc.v1.DocService.GetExportJob:output_type -> doc.v1.GetExportJobResponse
	30, // 49: doc.v1.DocService.DownloadExport:output_type -> doc.v1.DownloadExportResponse
	41, // [41:50] is the sub-list for method output_type
	32, // [32:41] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_shared_proto_doc_v1_doc_proto_init() }
func file_shared_proto_doc_v1_doc_proto_init() {
	if File_shared_proto_doc_v1_doc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_doc_v1_doc_proto_rawDesc), len(file_shared_proto_doc_v1_doc_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_doc_v1_doc_proto_goTypes,
		DependencyIndexes: file_shared_proto_doc_v1_doc_proto_depIdxs,
		EnumInfos:         file_shared_proto_doc_v1_doc_proto_enumTypes,
		MessageInfos:      file_shared_proto_doc_v1_doc_proto_msgTypes,
	}.Build()
	File_shared_proto_doc_v1_doc_proto = out.File
	file_shared_proto_doc_v1_doc_proto_goTypes = nil
	file_shared_proto_doc_v1_doc_proto_depIdxs = nil
}
