// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: shared/proto/notification/v1/notification.proto

package notificationv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NotificationChannel represents the delivery channel.
type NotificationChannel int32

const (
	NotificationChannel_NOTIFICATION_CHANNEL_UNSPECIFIED NotificationChannel = 0
	NotificationChannel_NOTIFICATION_CHANNEL_IN_APP      NotificationChannel = 1
	NotificationChannel_NOTIFICATION_CHANNEL_EMAIL       NotificationChannel = 2
	NotificationChannel_NOTIFICATION_CHANNEL_PUSH        NotificationChannel = 3
	NotificationChannel_NOTIFICATION_CHANNEL_SMS         NotificationChannel = 4
)

// Enum value maps for NotificationChannel.
var (
	NotificationChannel_name = map[int32]string{
		0: "NOTIFICATION_CHANNEL_UNSPECIFIED",
		1: "NOTIFICATION_CHANNEL_IN_APP",
		2: "NOTIFICATION_CHANNEL_EMAIL",
		3: "NOTIFICATION_CHANNEL_PUSH",
		4: "NOTIFICATION_CHANNEL_SMS",
	}
	NotificationChannel_value = map[string]int32{
		"NOTIFICATION_CHANNEL_UNSPECIFIED": 0,
		"NOTIFICATION_CHANNEL_IN_APP":      1,
		"NOTIFICATION_CHANNEL_EMAIL":       2,
		"NOTIFICATION_CHANNEL_PUSH":        3,
		"NOTIFICATION_CHANNEL_SMS":         4,
	}
)

func (x NotificationChannel) Enum() *NotificationChannel {
	p := new(NotificationChannel)
	*p = x
	return p
}

func (x NotificationChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_notification_v1_notification_proto_enumTypes[0].Descriptor()
}

func (NotificationChannel) Type() protoreflect.EnumType {
	return &file_shared_proto_notification_v1_notification_proto_enumTypes[0]
}

func (x NotificationChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationChannel.Descriptor instead.
func (NotificationChannel) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

// NotificationStatus represents the read state.
type NotificationStatus int32

const (
	NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED NotificationStatus = 0
	NotificationStatus_NOTIFICATION_STATUS_UNREAD      NotificationStatus = 1
	NotificationStatus_NOTIFICATION_STATUS_READ        NotificationStatus = 2
	NotificationStatus_NOTIFICATION_STATUS_ARCHIVED    NotificationStatus = 3
)

// Enum value maps for NotificationStatus.
var (
	NotificationStatus_name = map[int32]string{
		0: "NOTIFICATION_STATUS_UNSPECIFIED",
		1: "NOTIFICATION_STATUS_UNREAD",
		2: "NOTIFICATION_STATUS_READ",
		3: "NOTIFICATION_STATUS_ARCHIVED",
	}
	NotificationStatus_value = map[string]int32{
		"NOTIFICATION_STATUS_UNSPECIFIED": 0,
		"NOTIFICATION_STATUS_UNREAD":      1,
		"NOTIFICATION_STATUS_READ":        2,
		"NOTIFICATION_STATUS_ARCHIVED":    3,
	}
)

func (x NotificationStatus) Enum() *NotificationStatus {
	p := new(NotificationStatus)
	*p = x
	return p
}

func (x NotificationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_notification_v1_notification_proto_enumTypes[1].Descriptor()
}

func (NotificationStatus) Type() protoreflect.EnumType {
	return &file_shared_proto_notification_v1_notification_proto_enumTypes[1]
}

func (x NotificationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationStatus.Descriptor instead.
func (NotificationStatus) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

// NotificationPriority represents urgency.
type NotificationPriority int32

const (
	NotificationPriority_NOTIFICATION_PRIORITY_UNSPECIFIED NotificationPriority = 0
	NotificationPriority_NOTIFICATION_PRIORITY_LOW         NotificationPriority = 1
	NotificationPriority_NOTIFICATION_PRIORITY_NORMAL      NotificationPriority = 2
	NotificationPriority_NOTIFICATION_PRIORITY_HIGH        NotificationPriority = 3
	NotificationPriority_NOTIFICATION_PRIORITY_URGENT      NotificationPriority = 4
)

// Enum value maps for NotificationPriority.
var (
	NotificationPriority_name = map[int32]string{
		0: "NOTIFICATION_PRIORITY_UNSPECIFIED",
		1: "NOTIFICATION_PRIORITY_LOW",
		2: "NOTIFICATION_PRIORITY_NORMAL",
		3: "NOTIFICATION_PRIORITY_HIGH",
		4: "NOTIFICATION_PRIORITY_URGENT",
	}
	NotificationPriority_value = map[string]int32{
		"NOTIFICATION_PRIORITY_UNSPECIFIED": 0,
		"NOTIFICATION_PRIORITY_LOW":         1,
		"NOTIFICATION_PRIORITY_NORMAL":      2,
		"NOTIFICATION_PRIORITY_HIGH":        3,
		"NOTIFICATION_PRIORITY_URGENT":      4,
	}
)

func (x NotificationPriority) Enum() *NotificationPriority {
	p := new(NotificationPriority)
	*p = x
	return p
}

func (x NotificationPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_notification_v1_notification_proto_enumTypes[2].Descriptor()
}

func (NotificationPriority) Type() protoreflect.EnumType {
	return &file_shared_proto_notification_v1_notification_proto_enumTypes[2]
}

func (x NotificationPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationPriority.Descriptor instead.
func (NotificationPriority) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_notification_v1_notification_proto_rawDescGZIP(), []int{2}
}

// Notification represents a single notification.
type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Channel       NotificationChannel    `protobuf:"varint,6,opt,name=channel,proto3,enum=notification.v1.NotificationChannel" json:"channel,omitempty"`
	Priority      NotificationPriority   `protobuf:"varint,7,opt,name=priority,proto3,enum=notification.v1.NotificationPriority" json:"priority,omitempty"`
	Status        NotificationStatus     `protobuf:"varint,8,opt,name=status,proto3,enum=notification.v1.NotificationStatus" json:"status,omitempty"`
	ActionUrl     string                 `protobuf:"bytes,9,opt,name=action_url,json=actionUrl,proto3" json:"action_url,omitempty"` // optional deep link
	Metadata      map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ReadAt        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=read_at,json=readAt,proto3" json:"read_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_shared_proto_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Notification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Notification) GetChannel() NotificationChannel {
	if x != nil {
		return x.Channel
	}
	return NotificationChannel_NOTIFICATION_CHANNEL_UNSPECIFIED
}

func (x *Notification) GetPriority() NotificationPriority {
	if x != nil {
		return x.Priority
	}
	return NotificationPriority_NOTIFICATION_PRIORITY_UNSPECIFIED
}

func (x *Notification) GetStatus() NotificationStatus {
	if x != nil {
		return x.Status
	}
	return NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED
}

func (x *Notification) GetActionUrl() string {
	if x != nil {
		return x.ActionUrl
	}
	return ""
}

func (x *Notification) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Notification) GetReadAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadAt
	}
	return nil
}

// NotificationPreference controls per-channel settings for a user.
type NotificationPreference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Channel       NotificationChannel    `protobuf:"varint,3,opt,name=channel,proto3,enum=notification.v1.NotificationChannel" json:"channel,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Settings      map[string]string      `protobuf:"bytes,5,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // channel-specific settings (e.g. email address, push token)
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationPreference) Reset() {
	*x = NotificationPreference{}
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationPreference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationPreference) ProtoMessage() {}

func (x *NotificationPreference) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationPreference.ProtoReflect.Descriptor instead.
func (*NotificationPreference) Descriptor() ([]byte, []int) {
	return file_shared_proto_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationPreference) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotificationPreference) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *NotificationPreference) GetChannel() NotificationChannel {
	if x != nil {
		return x.Channel
	}
	return NotificationChannel_NOTIFICATION_CHANNEL_UNSPECIFIED
}

func (x *NotificationPreference) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *NotificationPreference) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *NotificationPreference) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// SendNotificationRequest triggers sending a notification.
type SendNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Channel       NotificationChannel    `protobuf:"varint,4,opt,name=channel,proto3,enum=notification.v1.NotificationChannel" json:"channel,omitempty"`
	Priority      NotificationPriority   `protobuf:"varint,5,opt,name=priority,proto3,enum=notification.v1.NotificationPriority" json:"priority,omitempty"`
	ActionUrl     string                 `protobuf:"bytes,6,opt,name=action_url,json=actionUrl,proto3" json:"action_url,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_notification_v1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *SendNotificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendNotificationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendNotificationRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SendNotificationRequest) GetChannel() NotificationChannel {
	if x != nil {
		return x.Channel
	}
	return NotificationChannel_NOTIFICATION_CHANNEL_UNSPECIFIED
}

func (x *SendNotificationRequest) GetPriority() NotificationPriority {
	if x != nil {
		return x.Priority
	}
	return NotificationPriority_NOTIFICATION_PRIORITY_UNSPECIFIED
}

func (x *SendNotificationRequest) GetActionUrl() string {
	if x != nil {
		return x.ActionUrl
	}
	return ""
}

func (x *SendNotificationRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// SendNotificationResponse confirms the notification was sent.
type SendNotificationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_notification_v1_notification_proto_rawDescGZIP(), []int{3}
}

func (x *SendNotificationResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

// ListNotificationsRequest lists notifications for the current user.
type ListNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                             // optional filter by status name
	Channel       NotificationChannel    `protobuf:"varint,2,opt,name=channel,proto3,enum=notification.v1.NotificationChannel" json:"channel,omitempty"` // optional filter
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_notification_v1_notification_proto_rawDescGZIP(), []int{4}
}

func (x *ListNotificationsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListNotificationsRequest) GetChannel() NotificationChannel {
	if x != nil {
		return x.Channel
	}
	return NotificationChannel_NOTIFICATION_CHANNEL_UNSPECIFIED
}

func (x *ListNotificationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListNotificationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ListNotificationsResponse returns paginated notifications.
type ListNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Notification        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Pages         int32                  `protobuf:"varint,4,opt,name=pages,proto3" json:"pages,omitempty"`
	UnreadCount   int32                  `protobuf:"varint,5,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_notification_v1_notification_proto_rawDescGZIP(), []int{5}
}

func (x *ListNotificationsResponse) GetItems() []*Notification {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListNotificationsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListNotificationsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListNotificationsResponse) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *ListNotificationsResponse) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

// MarkReadRequest marks one or all notifications as read.
type MarkReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"` // if empty, marks all as read
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkReadRequest) Reset() {
	*x = MarkReadRequest{}
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadRequest) ProtoMessage() {}

func (x *MarkReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadRequest.ProtoReflect.Descriptor instead.
func (*MarkReadRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_notification_v1_notification_proto_rawDescGZIP(), []int{6}
}

func (x *MarkReadRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

// MarkReadResponse confirms the operation.
type MarkReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MarkedCount   int32                  `protobuf:"varint,2,opt,name=marked_count,json=markedCount,proto3" json:"marked_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadResponse) Reset() {
	*x = MarkReadResponse{}
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadResponse) ProtoMessage() {}

func (x *MarkReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadResponse.ProtoReflect.Descriptor instead.
func (*MarkReadResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_notification_v1_notification_proto_rawDescGZIP(), []int{7}
}

func (x *MarkReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MarkReadResponse) GetMarkedCount() int32 {
	if x != nil {
		return x.MarkedCount
	}
	return 0
}

// GetPreferencesRequest fetches notification preferences.
type GetPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesRequest) Reset() {
	*x = GetPreferencesRequest{}
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesRequest) ProtoMessage() {}

func (x *GetPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesRequest.ProtoReflect.Descriptor instead.
func (*GetPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_notification_v1_notification_proto_rawDescGZIP(), []int{8}
}

// GetPreferencesResponse returns per-channel preferences.
type GetPreferencesResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Preferences   []*NotificationPreference `protobuf:"bytes,1,rep,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesResponse) Reset() {
	*x = GetPreferencesResponse{}
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesResponse) ProtoMessage() {}

func (x *GetPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesResponse.ProtoReflect.Descriptor instead.
func (*GetPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_notification_v1_notification_proto_rawDescGZIP(), []int{9}
}

func (x *GetPreferencesResponse) GetPreferences() []*NotificationPreference {
	if x != nil {
		return x.Preferences
	}
	return nil
}

// UpdatePreferencesRequest updates notification preferences.
type UpdatePreferencesRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Preferences   []*NotificationPreference `protobuf:"bytes,1,rep,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePreferencesRequest) Reset() {
	*x = UpdatePreferencesRequest{}
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesRequest) ProtoMessage() {}

func (x *UpdatePreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdatePreferencesRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_notification_v1_notification_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePreferencesRequest) GetPreferences() []*NotificationPreference {
	if x != nil {
		return x.Preferences
	}
	return nil
}

// UpdatePreferencesResponse confirms the update.
type UpdatePreferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePreferencesResponse) Reset() {
	*x = UpdatePreferencesResponse{}
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesResponse) ProtoMessage() {}

func (x *UpdatePreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferencesResponse.ProtoReflect.Descriptor instead.
func (*UpdatePreferencesResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_notification_v1_notification_proto_rawDescGZIP(), []int{11}
}

func (x *UpdatePreferencesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// SubscribeRequest starts a real-time notification stream.
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // optional; if empty, uses authenticated user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_notification_v1_notification_proto_rawDescGZIP(), []int{12}
}

func (x *SubscribeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// SubscribeEvent is a real-time push notification event.
type SubscribeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *Notification          `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEvent) Reset() {
	*x = SubscribeEvent{}
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEvent) ProtoMessage() {}

func (x *SubscribeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_notification_v1_notification_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEvent.ProtoReflect.Descriptor instead.
func (*SubscribeEvent) Descriptor() ([]byte, []int) {
	return file_shared_proto_notification_v1_notification_proto_rawDescGZIP(), []int{13}
}

func (x *SubscribeEvent) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

var File_shared_proto_notification_v1_notification_proto protoreflect.FileDescriptor

const file_shared_proto_notification_v1_notification_proto_rawDesc = "" +
	"\n" +
	"/shared/proto/notification/v1/notification.proto\x12\x0fnotification.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\x04\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12>\n" +
	"\achannel\x18\x06 \x01(\x0e2$.notification.v1.NotificationChannelR\achannel\x12A\n" +
	"\bpriority\x18\a \x01(\x0e2%.notification.v1.NotificationPriorityR\bpriority\x12;\n" +
	"\x06status\x18\b \x01(\x0e2#.notification.v1.NotificationStatusR\x06status\x12\x1d\n" +
	"\n" +
	"action_url\x18\t \x01(\tR\tactionUrl\x12G\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2+.notification.v1.Notification.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x123\n" +
	"\aread_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x06readAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf3\x02\n" +
	"\x16NotificationPreference\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12>\n" +
	"\achannel\x18\x03 \x01(\x0e2$.notification.v1.NotificationChannelR\achannel\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12Q\n" +
	"\bsettings\x18\x05 \x03(\v25.notification.v1.NotificationPreference.SettingsEntryR\bsettings\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x03\n" +
	"\x17SendNotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12>\n" +
	"\achannel\x18\x04 \x01(\x0e2$.notification.v1.NotificationChannelR\achannel\x12A\n" +
	"\bpriority\x18\x05 \x01(\x0e2%.notification.v1.NotificationPriorityR\bpriority\x12\x1d\n" +
	"\n" +
	"action_url\x18\x06 \x01(\tR\tactionUrl\x12R\n" +
	"\bmetadata\x18\a \x03(\v26.notification.v1.SendNotificationRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x18SendNotificationResponse\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\"\xa3\x01\n" +
	"\x18ListNotificationsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12>\n" +
	"\achannel\x18\x02 \x01(\x0e2$.notification.v1.NotificationChannelR\achannel\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xb3\x01\n" +
	"\x19ListNotificationsResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.notification.v1.NotificationR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05pages\x18\x04 \x01(\x05R\x05pages\x12!\n" +
	"\funread_count\x18\x05 \x01(\x05R\vunreadCount\":\n" +
	"\x0fMarkReadRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\"O\n" +
	"\x10MarkReadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fmarked_count\x18\x02 \x01(\x05R\vmarkedCount\"\x17\n" +
	"\x15GetPreferencesRequest\"c\n" +
	"\x16GetPreferencesResponse\x12I\n" +
	"\vpreferences\x18\x01 \x03(\v2'.notification.v1.NotificationPreferenceR\vpreferences\"e\n" +
	"\x18UpdatePreferencesRequest\x12I\n" +
	"\vpreferences\x18\x01 \x03(\v2'.notification.v1.NotificationPreferenceR\vpreferences\"5\n" +
	"\x19UpdatePreferencesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"+\n" +
	"\x10SubscribeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"S\n" +
	"\x0eSubscribeEvent\x12A\n" +
	"\fnotification\x18\x01 \x01(\v2\x1d.notification.v1.NotificationR\fnotification*\xb9\x01\n" +
	"\x13NotificationChannel\x12$\n" +
	" NOTIFICATION_CHANNEL_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bNOTIFICATION_CHANNEL_IN_APP\x10\x01\x12\x1e\n" +
	"\x1aNOTIFICATION_CHANNEL_EMAIL\x10\x02\x12\x1d\n" +
	"\x19NOTIFICATION_CHANNEL_PUSH\x10\x03\x12\x1c\n" +
	"\x18NOTIFICATION_CHANNEL_SMS\x10\x04*\x99\x01\n" +
	"\x12NotificationStatus\x12#\n" +
	"\x1fNOTIFICATION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aNOTIFICATION_STATUS_UNREAD\x10\x01\x12\x1c\n" +
	"\x18NOTIFICATION_STATUS_READ\x10\x02\x12 \n" +
	"\x1cNOTIFICATION_STATUS_ARCHIVED\x10\x03*\xc0\x01\n" +
	"\x14NotificationPriority\x12%\n" +
	"!NOTIFICATION_PRIORITY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19NOTIFICATION_PRIORITY_LOW\x10\x01\x12 \n" +
	"\x1cNOTIFICATION_PRIORITY_NORMAL\x10\x02\x12\x1e\n" +
	"\x1aNOTIFICATION_PRIORITY_HIGH\x10\x03\x12 \n" +
	"\x1cNOTIFICATION_PRIORITY_URGENT\x10\x042\xcb\x06\n" +
	"\x13NotificationService\x12\x89\x01\n" +
	"\x10SendNotification\x12(.notification.v1.SendNotificationRequest\x1a).notification.v1.SendNotificationResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/notifications\x12\x89\x01\n" +
	"\x11ListNotifications\x12).notification.v1.ListNotificationsRequest\x1a*.notification.v1.ListNotificationsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/notifications\x12v\n" +
	"\bMarkRead\x12 .notification.v1.MarkReadRequest\x1a!.notification.v1.MarkReadResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/notifications/read\x12\x8c\x01\n" +
	"\x0eGetPreferences\x12&.notification.v1.GetPreferencesRequest\x1a'.notification.v1.GetPreferencesResponse\")\x82\xd3\xe4\x93\x02#\x12!/api/v1/notifications/preferences\x12\x98\x01\n" +
	"\x11UpdatePreferences\x12).notification.v1.UpdatePreferencesRequest\x1a*.notification.v1.UpdatePreferencesResponse\",\x82\xd3\xe4\x93\x02&:\x01*\x1a!/api/v1/notifications/preferences\x12z\n" +
	"\tSubscribe\x12!.notification.v1.SubscribeRequest\x1a\x1f.notification.v1.SubscribeEvent\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/notifications/subscribe0\x01BEZCsovereign-ai-compliance/shared/proto/notification/v1;notificationv1b\x06proto3"

var (
	file_shared_proto_notification_v1_notification_proto_rawDescOnce sync.Once
	file_shared_proto_notification_v1_notification_proto_rawDescData []byte
)

func file_shared_proto_notification_v1_notification_proto_rawDescGZIP() []byte {
	file_shared_proto_notification_v1_notification_proto_rawDescOnce.Do(func() {
		file_shared_proto_notification_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_notification_v1_notification_proto_rawDesc), len(file_shared_proto_notification_v1_notification_proto_rawDesc)))
	})
	return file_shared_proto_notification_v1_notification_proto_rawDescData
}

var file_shared_proto_notification_v1_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_shared_proto_notification_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_shared_proto_notification_v1_notification_proto_goTypes = []any{
	(NotificationChannel)(0),          // 0: notification.v1.NotificationChannel
	(NotificationStatus)(0),           // 1: notification.v1.NotificationStatus
	(NotificationPriority)(0),         // 2: notification.v1.NotificationPriority
	(*Notification)(nil),              // 3: notification.v1.Notification
	(*NotificationPreference)(nil),    // 4: notification.v1.NotificationPreference
	(*SendNotificationRequest)(nil),   // 5: notification.v1.SendNotificationRequest
	(*SendNotificationResponse)(nil),  // 6: notification.v1.SendNotificationResponse
	(*ListNotificationsRequest)(nil),  // 7: notification.v1.ListNotificationsRequest
	(*ListNotificationsResponse)(nil), // 8: notification.v1.ListNotificationsResponse
	(*MarkReadRequest)(nil),           // 9: notification.v1.MarkReadRequest
	(*MarkReadResponse)(nil),          // 10: notification.v1.MarkReadResponse
	(*GetPreferencesRequest)(nil),     // 11: notification.v1.GetPreferencesRequest
	(*GetPreferencesResponse)(nil),    // 12: notification.v1.GetPreferencesResponse
	(*UpdatePreferencesRequest)(nil),  // 13: notification.v1.UpdatePreferencesRequest
	(*UpdatePreferencesResponse)(nil), // 14: notification.v1.UpdatePreferencesResponse
	(*SubscribeRequest)(nil),          // 15: notification.v1.SubscribeRequest
	(*SubscribeEvent)(nil),            // 16: notification.v1.SubscribeEvent
	nil,                               // 17: notification.v1.Notification.MetadataEntry
	nil,                               // 18: notification.v1.NotificationPreference.SettingsEntry
	nil,                               // 19: notification.v1.SendNotificationRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil),     // 20: google.protobuf.Timestamp
}
var file_shared_proto_notification_v1_notification_proto_depIdxs = []int32{
	0,  // 0: notification.v1.Notification.channel:type_name -> notification.v1.NotificationChannel
	2,  // 1: notification.v1.Notification.priority:type_name -> notification.v1.NotificationPriority
	1,  // 2: notification.v1.Notification.status:type_name -> notification.v1.NotificationStatus
	17, // 3: notification.v1.Notification.metadata:type_name -> notification.v1.Notification.MetadataEntry
	20, // 4: notification.v1.Notification.created_at:type_name -> google.protobuf.Timestamp
	20, // 5: notification.v1.Notification.read_at:type_name -> google.protobuf.Timestamp
	0,  // 6: notification.v1.NotificationPreference.channel:type_name -> notification.v1.NotificationChannel
	18, // 7: notification.v1.NotificationPreference.settings:type_name -> notification.v1.NotificationPreference.SettingsEntry
	20, // 8: notification.v1.NotificationPreference.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 9: notification.v1.SendNotificationRequest.channel:type_name -> notification.v1.NotificationChannel
	2,  // 10: notification.v1.SendNotificationRequest.priority:type_name -> notification.v1.NotificationPriority
	19, // 11: notification.v1.SendNotificationRequest.metadata:type_name -> notification.v1.SendNotificationRequest.MetadataEntry
	0,  // 12: notification.v1.ListNotificationsRequest.channel:type_name -> notification.v1.NotificationChannel
	3,  // 13: notification.v1.ListNotificationsResponse.items:type_name -> notification.v1.Notification
	4,  // 14: notification.v1.GetPreferencesResponse.preferences:type_name -> notification.v1.NotificationPreference
	4,  // 15: notification.v1.UpdatePreferencesRequest.preferences:type_name -> notification.v1.NotificationPreference
	3,  // 16: notification.v1.SubscribeEvent.notification:type_name -> notification.v1.Notification
	5,  // 17: notification.v1.NotificationService.SendNotification:input_type -> notification.v1.SendNotificationRequest
	7,  // 18: notification.v1.NotificationService.ListNotifications:input_type -> notification.v1.ListNotificationsRequest
	9,  // 19: notification.v1.NotificationService.MarkRead:input_type -> notification.v1.MarkReadRequest
	11, // 20: notification.v1.NotificationService.GetPreferences:input_type -> notification.v1.GetPreferencesRequest
	13, // 21: notification.v1.NotificationService.UpdatePreferences:input_type -> notification.v1.UpdatePreferencesRequest
	15, // 22: notification.v1.NotificationService.Subscribe:input_type -> notification.v1.SubscribeRequest
	6,  // 23: notification.v1.NotificationService.SendNotification:output_type -> notification.v1.SendNotificationResponse
	8,  // 24: notification.v1.NotificationService.ListNotifications:output_type -> notification.v1.ListNotificationsResponse
	10, // 25: notification.v1.NotificationService.MarkRead:output_type -> notification.v1.MarkReadResponse
	12, // 26: notification.v1.NotificationService.GetPreferences:output_type -> notification.v1.GetPreferencesResponse
	14, // 27: notification.v1.NotificationService.UpdatePreferences:output_type -> notification.v1.UpdatePreferencesResponse
	16, // 28: notification.v1.NotificationService.Subscribe:output_type -> notification.v1.SubscribeEvent
	23, // [23:29] is the sub-list for method output_type
	17, // [17:23] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_shared_proto_notification_v1_notification_proto_init() }
func file_shared_proto_notification_v1_notification_proto_init() {
	if File_shared_proto_notification_v1_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_notification_v1_notification_proto_rawDesc), len(file_shared_proto_notification_v1_notification_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_notification_v1_notification_proto_goTypes,
		DependencyIndexes: file_shared_proto_notification_v1_notification_proto_depIdxs,
		EnumInfos:         file_shared_proto_notification_v1_notification_proto_enumTypes,
		MessageInfos:      file_shared_proto_notification_v1_notification_proto_msgTypes,
	}.Build()
	File_shared_proto_notification_v1_notification_proto = out.File
	file_shared_proto_notification_v1_notification_proto_goTypes = nil
	file_shared_proto_notification_v1_notification_proto_depIdxs = nil
}
